-- =============================================
-- BrightEnroll_DES Database Export Script
-- This script exports the complete database schema and data
-- Run this script in SSMS to generate a complete database backup
-- =============================================

USE [DB_BrightEnroll_DES];
GO

-- =============================================
-- PART 1: DROP EXISTING OBJECTS (if recreating)
-- =============================================
-- Uncomment the following lines if you want to drop existing objects
-- WARNING: This will delete all data!

/*
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[tbl_Users]') AND type in (N'U'))
    DROP TABLE [dbo].[tbl_Users];
GO
*/

-- =============================================
-- PART 2: CREATE TABLES
-- =============================================

-- Create tbl_Users table
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='tbl_Users' and xtype='U')
BEGIN
    CREATE TABLE [dbo].[tbl_Users](
        [user_ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [system_ID] VARCHAR(50) NOT NULL UNIQUE,
        [first_name] VARCHAR(50) NOT NULL,
        [mid_name] VARCHAR(50) NULL,
        [last_name] VARCHAR(50) NOT NULL,
        [suffix] VARCHAR(10) NULL,
        [birthdate] DATE NOT NULL,
        [age] TINYINT NOT NULL,
        [gender] VARCHAR(20) NOT NULL,
        [contact_num] VARCHAR(20) NOT NULL,
        [user_role] VARCHAR(50) NOT NULL,
        [email] VARCHAR(150) NOT NULL UNIQUE,
        [password] VARCHAR(255) NOT NULL,
        [date_hired] DATETIME NOT NULL
    );
    
    PRINT 'Table [dbo].[tbl_Users] created successfully.';
END
ELSE
BEGIN
    PRINT 'Table [dbo].[tbl_Users] already exists.';
END
GO

-- =============================================
-- PART 3: INSERT DATA
-- =============================================

-- Insert initial admin user (if not exists)
IF NOT EXISTS (SELECT * FROM [dbo].[tbl_Users] WHERE [system_ID] = 'BDES-0001')
BEGIN
    -- Note: Password hash for "Admin123456" - will be generated by application seeder
    -- This is a placeholder. The actual hash should be generated by BCrypt in the application
    INSERT INTO [dbo].[tbl_Users] 
        ([system_ID], [first_name], [mid_name], [last_name], [suffix], 
         [birthdate], [age], [gender], [contact_num], [user_role], [email], [password], [date_hired])
    VALUES 
        ('BDES-0001', 'Josh', NULL, 'Vanderson', NULL, 
         '2000-01-01', 24, 'male', '09366669571', 'Admin', 'joshvanderson01@gmail.com', 
         '$2a$11$PLACEHOLDER_HASH_WILL_BE_GENERATED_BY_APPLICATION', GETDATE());
    
    PRINT 'Initial admin user inserted.';
END
ELSE
BEGIN
    PRINT 'Initial admin user already exists.';
END
GO

-- =============================================
-- PART 4: CREATE INDEXES (Optional - for performance)
-- =============================================

-- Index on email for faster lookups
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_tbl_Users_Email' AND object_id = OBJECT_ID('dbo.tbl_Users'))
BEGIN
    CREATE INDEX IX_tbl_Users_Email ON [dbo].[tbl_Users]([email]);
    PRINT 'Index IX_tbl_Users_Email created.';
END
GO

-- Index on system_ID for faster lookups
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_tbl_Users_SystemID' AND object_id = OBJECT_ID('dbo.tbl_Users'))
BEGIN
    CREATE INDEX IX_tbl_Users_SystemID ON [dbo].[tbl_Users]([system_ID]);
    PRINT 'Index IX_tbl_Users_SystemID created.';
END
GO

-- =============================================
-- PART 5: VERIFY DATABASE SETUP
-- =============================================

PRINT '';
PRINT '========================================';
PRINT 'Database Setup Verification';
PRINT '========================================';
PRINT '';

-- Check table exists
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[tbl_Users]') AND type in (N'U'))
    PRINT '✓ Table [dbo].[tbl_Users] exists';
ELSE
    PRINT '✗ Table [dbo].[tbl_Users] does NOT exist';

-- Check user count
DECLARE @UserCount INT;
SELECT @UserCount = COUNT(*) FROM [dbo].[tbl_Users];
PRINT '✓ Total users in database: ' + CAST(@UserCount AS VARCHAR(10));

-- Check admin user exists
IF EXISTS (SELECT * FROM [dbo].[tbl_Users] WHERE [system_ID] = 'BDES-0001')
    PRINT '✓ Admin user (BDES-0001) exists';
ELSE
    PRINT '✗ Admin user (BDES-0001) does NOT exist';

PRINT '';
PRINT 'Database export script completed!';
PRINT 'Note: Password hashes should be generated by the application seeder.';
GO

