-- =============================================
-- BrightEnroll_DES Database Initialization Script
-- Run this script on a new device to set up the database
-- =============================================

-- =============================================
-- STEP 1: CREATE DATABASE (if it doesn't exist)
-- =============================================

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'DB_BrightEnroll_DES')
BEGIN
    CREATE DATABASE [DB_BrightEnroll_DES];
    PRINT 'Database [DB_BrightEnroll_DES] created successfully.';
END
ELSE
BEGIN
    PRINT 'Database [DB_BrightEnroll_DES] already exists.';
END
GO

-- =============================================
-- STEP 2: USE THE DATABASE
-- =============================================

USE [DB_BrightEnroll_DES];
GO

-- =============================================
-- STEP 3: CREATE TABLES
-- =============================================

-- Create tbl_Users table
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='tbl_Users' and xtype='U')
BEGIN
    CREATE TABLE [dbo].[tbl_Users](
        [user_ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [system_ID] VARCHAR(50) NOT NULL UNIQUE,
        [first_name] VARCHAR(50) NOT NULL,
        [mid_name] VARCHAR(50) NULL,
        [last_name] VARCHAR(50) NOT NULL,
        [suffix] VARCHAR(10) NULL,
        [birthdate] DATE NOT NULL,
        [age] TINYINT NOT NULL,
        [gender] VARCHAR(20) NOT NULL,
        [contact_num] VARCHAR(20) NOT NULL,
        [user_role] VARCHAR(50) NOT NULL,
        [email] VARCHAR(150) NOT NULL UNIQUE,
        [password] VARCHAR(255) NOT NULL,
        [date_hired] DATETIME NOT NULL
    );
    
    PRINT 'Table [dbo].[tbl_Users] created successfully.';
END
ELSE
BEGIN
    PRINT 'Table [dbo].[tbl_Users] already exists.';
END
GO

-- =============================================
-- STEP 4: CREATE INDEXES
-- =============================================

-- Index on email for faster lookups
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_tbl_Users_Email' AND object_id = OBJECT_ID('dbo.tbl_Users'))
BEGIN
    CREATE INDEX IX_tbl_Users_Email ON [dbo].[tbl_Users]([email]);
    PRINT 'Index IX_tbl_Users_Email created.';
END
GO

-- Index on system_ID for faster lookups
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_tbl_Users_SystemID' AND object_id = OBJECT_ID('dbo.tbl_Users'))
BEGIN
    CREATE INDEX IX_tbl_Users_SystemID ON [dbo].[tbl_Users]([system_ID]);
    PRINT 'Index IX_tbl_Users_SystemID created.';
END
GO

-- =============================================
-- STEP 5: INSERT INITIAL DATA (Optional)
-- =============================================
-- The application seeder will create the admin user automatically
-- If you want to pre-populate data, uncomment and modify the section below

/*
-- Insert initial admin user
IF NOT EXISTS (SELECT * FROM [dbo].[tbl_Users] WHERE [system_ID] = 'BDES-0001')
BEGIN
    -- Note: The password hash will be generated by the application seeder
    -- This is just a placeholder - the app will create the actual user with proper BCrypt hash
    INSERT INTO [dbo].[tbl_Users] 
        ([system_ID], [first_name], [mid_name], [last_name], [suffix], 
         [birthdate], [age], [gender], [contact_num], [user_role], [email], [password], [date_hired])
    VALUES 
        ('BDES-0001', 'Josh', NULL, 'Vanderson', NULL, 
         '2000-01-01', 24, 'male', '09366669571', 'Admin', 'joshvanderson01@gmail.com', 
         'PLACEHOLDER', GETDATE());
    
    PRINT 'Initial admin user inserted (password will be set by application seeder).';
END
GO
*/

-- =============================================
-- STEP 6: VERIFY SETUP
-- =============================================

PRINT '';
PRINT '========================================';
PRINT 'Database Initialization Complete';
PRINT '========================================';
PRINT '';

-- Check table exists
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[tbl_Users]') AND type in (N'U'))
    PRINT '✓ Table [dbo].[tbl_Users] exists';
ELSE
    PRINT '✗ Table [dbo].[tbl_Users] does NOT exist';

-- Check user count
DECLARE @UserCount INT;
SELECT @UserCount = COUNT(*) FROM [dbo].[tbl_Users];
PRINT '✓ Total users in database: ' + CAST(@UserCount AS VARCHAR(10));

PRINT '';
PRINT 'Next Steps:';
PRINT '1. Run the application - it will automatically seed the admin user';
PRINT '2. Or manually insert users using the application interface';
PRINT '';

GO

