using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.IO;
using BrightEnroll_DES.Data.Models;
using QuestPdfColors = QuestPDF.Helpers.Colors;

namespace BrightEnroll_DES.Services.QuestPDF;

public class CustomerContractPdfGenerator
{
    private byte[]? _logoBytes;

    private byte[] GetLogoBytes()
    {
        if (_logoBytes != null) return _logoBytes;
        
        var logoPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "reportPDF.png");
        if (File.Exists(logoPath))
        {
            _logoBytes = File.ReadAllBytes(logoPath);
        }
        return _logoBytes ?? Array.Empty<byte>();
    }

    public byte[] GenerateCustomerContract(Customer customer, string generatedBy, List<string> selectedModules)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.PageColor(QuestPdfColors.White);
                page.DefaultTextStyle(x => x.FontSize(10));

                // Header with Logo - Improved Layout
                page.Header()
                    .PaddingBottom(10)
                    .Column(headerColumn =>
                    {
                        headerColumn.Item().Row(headerRow =>
                        {
                            // Left side: Logo and Company Info
                            var logoBytes = GetLogoBytes();
                            if (logoBytes.Length > 0)
                            {
                                headerRow.ConstantItem(40).PaddingRight(10).Image(logoBytes).FitArea();
                            }
                            
                            headerRow.RelativeItem().Column(companyCol =>
                            {
                                companyCol.Item().Text("BRIGHTENROLL").FontSize(18).Bold().FontColor(QuestPdfColors.Blue.Darken3);
                                companyCol.Item().PaddingTop(2).Text("ENROLLMENT MANAGEMENT SYSTEM").FontSize(11).FontColor(QuestPdfColors.Grey.Darken1);
                                companyCol.Item().PaddingTop(3).Text("SUPER ADMINISTRATOR").FontSize(9).FontColor(QuestPdfColors.Grey.Darken1);
                            });
                            
                            // Right side: Date and Generated By
                            headerRow.RelativeItem().AlignRight().Column(dateCol =>
                            {
                                dateCol.Item().AlignRight().Text($"Date: {DateTime.Now:MMMM dd, yyyy}").FontSize(9);
                                dateCol.Item().AlignRight().Text($"Time: {DateTime.Now:HH:mm}").FontSize(9);
                                dateCol.Item().PaddingTop(2).AlignRight().Text($"Generated by: {generatedBy}").FontSize(9);
                            });
                        });
                        
                        headerColumn.Item().PaddingTop(8).BorderBottom(2).BorderColor(QuestPdfColors.Blue.Darken2);
                    });

                // Content
                page.Content().PaddingVertical(10).Column(column =>
                {
                    // Title
                    column.Item().AlignCenter().Text("CUSTOMER CONTRACT & BILLING STATEMENT").FontSize(16).Bold().FontColor(QuestPdfColors.Blue.Darken3);
                    column.Item().PaddingTop(5).AlignCenter().Text($"Contract Code: {customer.CustomerCode}").FontSize(11).Bold();
                    
                    column.Item().PaddingTop(15);

                    // Section 1: Customer Information
                    column.Item().Text("1. CUSTOMER INFORMATION").FontSize(12).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                    column.Item().PaddingTop(5).Background(QuestPdfColors.Grey.Lighten5).Padding(10).Column(infoCol =>
                    {
                        infoCol.Item().Row(row =>
                        {
                            row.RelativeItem().Text("School Name:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                            row.RelativeItem(2).Text(customer.SchoolName).FontSize(10).Bold();
                        });
                        infoCol.Item().PaddingTop(3).Row(row =>
                        {
                            row.RelativeItem().Text("School Type:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                            row.RelativeItem(2).Text(customer.SchoolType ?? "N/A").FontSize(10);
                        });
                        infoCol.Item().PaddingTop(3).Row(row =>
                        {
                            row.RelativeItem().Text("Address:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                            row.RelativeItem(2).Text(customer.Address ?? "N/A").FontSize(10);
                        });
                        infoCol.Item().PaddingTop(3).Row(row =>
                        {
                            row.RelativeItem().Text("Contact Person:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                            row.RelativeItem(2).Text(customer.ContactPerson ?? "N/A").FontSize(10).Bold();
                        });
                        infoCol.Item().PaddingTop(3).Row(row =>
                        {
                            row.RelativeItem().Text("Position:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                            row.RelativeItem(2).Text(customer.ContactPosition ?? "N/A").FontSize(10);
                        });
                        infoCol.Item().PaddingTop(3).Row(row =>
                        {
                            row.RelativeItem().Text("Email:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                            row.RelativeItem(2).Text(customer.ContactEmail ?? "N/A").FontSize(10);
                        });
                        infoCol.Item().PaddingTop(3).Row(row =>
                        {
                            row.RelativeItem().Text("Phone:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                            row.RelativeItem(2).Text(customer.ContactPhone ?? "N/A").FontSize(10);
                        });
                        // Always show admin account section (credentials are generated during customer creation)
                        infoCol.Item().PaddingTop(5).BorderTop(1).BorderColor(QuestPdfColors.Grey.Lighten2).PaddingTop(5);
                        infoCol.Item().Text("Admin Account Credentials:").FontSize(9).Bold().FontColor(QuestPdfColors.Green.Darken2);
                        infoCol.Item().PaddingTop(2).Row(row =>
                        {
                            row.RelativeItem().Text("Username/Email:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                            row.RelativeItem(2).Text(customer.AdminUsername ?? "Will be generated upon creation").FontSize(9).FontFamily("Courier New").Bold();
                        });
                        infoCol.Item().PaddingTop(2).Row(row =>
                        {
                            row.RelativeItem().Text("Default Password:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                            row.RelativeItem(2).Text(customer.AdminPassword ?? "Admin123456").FontSize(9).FontFamily("Courier New").Bold();
                        });
                        infoCol.Item().PaddingTop(3).Text("⚠️ Please save these credentials securely. Change password after first login.").FontSize(8).FontColor(QuestPdfColors.Orange.Darken2).Italic();
                    });

                    column.Item().PaddingTop(15);

                    // Section 2: Billing & Payment Information
                    column.Item().Text("2. BILLING & PAYMENT INFORMATION").FontSize(12).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                    column.Item().PaddingTop(5).Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                        });
                        
                        var subtotal = customer.IsVatRegistered && customer.VatRate.HasValue 
                            ? customer.MonthlyFee / (1 + (customer.VatRate.Value / 100m))
                            : customer.MonthlyFee;
                        var vat = customer.MonthlyFee - subtotal;

                        table.Cell().Padding(5).Text("Subscription Plan:").FontSize(9);
                        table.Cell().Padding(5).Text(customer.SubscriptionPlan ?? "Custom").FontSize(9).Bold();
                        
                        table.Cell().Background(QuestPdfColors.Grey.Lighten4).Padding(5).Text("Monthly Fee (Subtotal):").FontSize(9);
                        table.Cell().Background(QuestPdfColors.Grey.Lighten4).Padding(5).AlignRight().Text($"₱{subtotal:N2}").FontSize(9).Bold();
                        
                        if (customer.IsVatRegistered && vat > 0)
                        {
                            table.Cell().Padding(5).Text($"VAT ({customer.VatRate}%):").FontSize(9);
                            table.Cell().Padding(5).AlignRight().Text($"₱{vat:N2}").FontSize(9);
                        }
                        
                        table.Cell().Background(QuestPdfColors.Blue.Lighten5).Padding(5).Text("Total Monthly Fee:").FontSize(10).Bold();
                        table.Cell().Background(QuestPdfColors.Blue.Lighten5).Padding(5).AlignRight().Text($"₱{customer.MonthlyFee:N2}").FontSize(11).Bold().FontColor(QuestPdfColors.Blue.Darken3);
                        
                        if (customer.ContractDurationMonths.HasValue)
                        {
                            var totalContract = customer.MonthlyFee * customer.ContractDurationMonths.Value;
                            table.Cell().Padding(5).Text($"Total Contract Value ({customer.ContractDurationMonths} months):").FontSize(9);
                            table.Cell().Padding(5).AlignRight().Text($"₱{totalContract:N2}").FontSize(10).Bold();
                        }
                    });

                    column.Item().PaddingTop(15);

                    // Section 3: Contract Details
                    column.Item().Text("3. CONTRACT DETAILS").FontSize(12).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                    column.Item().PaddingTop(5).Background(QuestPdfColors.Grey.Lighten5).Padding(10).Column(contractCol =>
                    {
                        contractCol.Item().Row(row =>
                        {
                            row.RelativeItem().Text("Contract Start Date:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                            row.RelativeItem(2).Text(customer.ContractStartDate?.ToString("MMMM dd, yyyy") ?? "N/A").FontSize(10).Bold();
                        });
                        contractCol.Item().PaddingTop(3).Row(row =>
                        {
                            row.RelativeItem().Text("Contract End Date:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                            row.RelativeItem(2).Text(customer.ContractEndDate?.ToString("MMMM dd, yyyy") ?? "N/A").FontSize(10).Bold();
                        });
                        contractCol.Item().PaddingTop(3).Row(row =>
                        {
                            row.RelativeItem().Text("Duration:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                            row.RelativeItem(2).Text($"{customer.ContractDurationMonths ?? 0} months").FontSize(10);
                        });
                        contractCol.Item().PaddingTop(3).Row(row =>
                        {
                            row.RelativeItem().Text("Status:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                            row.RelativeItem(2).Text(customer.Status).FontSize(10).Bold();
                        });
                        contractCol.Item().PaddingTop(3).Row(row =>
                        {
                            row.RelativeItem().Text("Auto Renewal:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                            row.RelativeItem(2).Text(customer.AutoRenewal ? "Yes" : "No").FontSize(10);
                        });
                        if (!string.IsNullOrWhiteSpace(customer.PaymentTerms))
                        {
                            contractCol.Item().PaddingTop(5).BorderTop(1).BorderColor(QuestPdfColors.Grey.Lighten2).PaddingTop(5);
                            contractCol.Item().Row(row =>
                            {
                                row.RelativeItem().Text("Payment Terms:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                                row.RelativeItem(2).Text(customer.PaymentTerms).FontSize(10);
                            });
                        }
                    });

                    column.Item().PaddingTop(15);

                    // Section 4: Modules/Features
                    column.Item().Text("4. INCLUDED MODULES & FEATURES").FontSize(12).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                    column.Item().PaddingTop(5).Background(QuestPdfColors.Grey.Lighten5).Padding(10).Column(modulesCol =>
                    {
                        // Helper function to get package price from module name
                        decimal GetPackagePriceFromName(string moduleName)
                        {
                            var nameLower = moduleName.ToLower();
                            if (nameLower.Contains("enrollment") || nameLower.Contains("academic"))
                                return 25000;
                            if (nameLower.Contains("hr") || nameLower.Contains("payroll"))
                                return 15000;
                            if (nameLower.Contains("finance"))
                                return 12000;
                            if (nameLower.Contains("inventory") || nameLower.Contains("asset"))
                                return 5000;
                            if (nameLower.Contains("core") || nameLower.Contains("always included"))
                                return 10000;
                            return 0;
                        }
                        
                        if (selectedModules != null && selectedModules.Any())
                        {
                            foreach (var module in selectedModules)
                            {
                                var price = GetPackagePriceFromName(module);
                                
                                modulesCol.Item().PaddingVertical(2).Row(row =>
                                {
                                    row.ConstantItem(20).Text("✓").FontSize(10).FontColor(QuestPdfColors.Green.Darken2);
                                    row.RelativeItem().Text(module).FontSize(10);
                                    if (price > 0)
                                    {
                                        row.RelativeItem().AlignRight().Text($"₱{price:N2}").FontSize(9).FontColor(QuestPdfColors.Grey.Darken1);
                                    }
                                });
                            }
                        }
                        else
                        {
                            modulesCol.Item().Text($"All modules included in {customer.SubscriptionPlan} plan").FontSize(10);
                        }
                    });

                    column.Item().PaddingTop(15);

                    // Section 5: BIR Compliance (if applicable)
                    if (customer.IsVatRegistered)
                    {
                        column.Item().Text("5. BIR COMPLIANCE INFORMATION").FontSize(12).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                        column.Item().PaddingTop(5).Background(QuestPdfColors.Grey.Lighten5).Padding(10).Column(birCol =>
                        {
                            if (!string.IsNullOrWhiteSpace(customer.BirTin))
                            {
                                birCol.Item().Row(row =>
                                {
                                    row.RelativeItem().Text("BIR TIN:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                                    row.RelativeItem(2).Text(customer.BirTin).FontSize(10).Bold();
                                });
                            }
                            if (!string.IsNullOrWhiteSpace(customer.BirBusinessName))
                            {
                                birCol.Item().PaddingTop(3).Row(row =>
                                {
                                    row.RelativeItem().Text("Business Name:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                                    row.RelativeItem(2).Text(customer.BirBusinessName).FontSize(10);
                                });
                            }
                            birCol.Item().PaddingTop(3).Row(row =>
                            {
                                row.RelativeItem().Text("VAT Registered:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                                row.RelativeItem(2).Text("Yes").FontSize(10).Bold().FontColor(QuestPdfColors.Green.Darken2);
                            });
                            if (customer.VatRate.HasValue)
                            {
                                birCol.Item().PaddingTop(3).Row(row =>
                                {
                                    row.RelativeItem().Text("VAT Rate:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                                    row.RelativeItem(2).Text($"{customer.VatRate}%").FontSize(10).Bold();
                                });
                            }
                        });
                        column.Item().PaddingTop(15);
                    }

                    // Section 6: Contract Terms & Services
                    if (!string.IsNullOrWhiteSpace(customer.WarrantyPeriod) || 
                        !string.IsNullOrWhiteSpace(customer.MaintenanceSchedule) ||
                        !string.IsNullOrWhiteSpace(customer.FreeServices) ||
                        !string.IsNullOrWhiteSpace(customer.TerminationClause) ||
                        !string.IsNullOrWhiteSpace(customer.SlaDetails) ||
                        !string.IsNullOrWhiteSpace(customer.ContractTermsText))
                    {
                        column.Item().Text("6. CONTRACT TERMS & SERVICES").FontSize(12).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                        column.Item().PaddingTop(5).Background(QuestPdfColors.Grey.Lighten5).Padding(10).Column(termsCol =>
                        {
                            if (!string.IsNullOrWhiteSpace(customer.WarrantyPeriod))
                            {
                                termsCol.Item().Row(row =>
                                {
                                    row.RelativeItem().Text("Warranty Period:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                                    row.RelativeItem(2).Text(customer.WarrantyPeriod).FontSize(10);
                                });
                                termsCol.Item().PaddingTop(3);
                            }
                            if (!string.IsNullOrWhiteSpace(customer.MaintenanceSchedule))
                            {
                                termsCol.Item().Row(row =>
                                {
                                    row.RelativeItem().Text("Maintenance Schedule:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                                    row.RelativeItem(2).Text(customer.MaintenanceSchedule).FontSize(10);
                                });
                                termsCol.Item().PaddingTop(3);
                            }
                            if (!string.IsNullOrWhiteSpace(customer.FreeServices))
                            {
                                termsCol.Item().Row(row =>
                                {
                                    row.RelativeItem().Text("Free Services:").FontSize(9).FontColor(QuestPdfColors.Grey.Darken2);
                                    row.RelativeItem(2).Text(customer.FreeServices).FontSize(10);
                                });
                                termsCol.Item().PaddingTop(3);
                            }
                            if (!string.IsNullOrWhiteSpace(customer.TerminationClause))
                            {
                                termsCol.Item().PaddingTop(5).BorderTop(1).BorderColor(QuestPdfColors.Grey.Lighten2).PaddingTop(5);
                                termsCol.Item().Text("Termination Clause:").FontSize(9).Bold().FontColor(QuestPdfColors.Grey.Darken2);
                                termsCol.Item().PaddingTop(2).Text(customer.TerminationClause).FontSize(9).LineHeight(1.4f);
                            }
                            if (!string.IsNullOrWhiteSpace(customer.SlaDetails))
                            {
                                termsCol.Item().PaddingTop(5).BorderTop(1).BorderColor(QuestPdfColors.Grey.Lighten2).PaddingTop(5);
                                termsCol.Item().Text("SLA Details:").FontSize(9).Bold().FontColor(QuestPdfColors.Grey.Darken2);
                                termsCol.Item().PaddingTop(2).Text(customer.SlaDetails).FontSize(9).LineHeight(1.4f);
                            }
                            if (!string.IsNullOrWhiteSpace(customer.ContractTermsText))
                            {
                                termsCol.Item().PaddingTop(5).BorderTop(1).BorderColor(QuestPdfColors.Grey.Lighten2).PaddingTop(5);
                                termsCol.Item().Text("Full Contract Terms:").FontSize(9).Bold().FontColor(QuestPdfColors.Grey.Darken2);
                                termsCol.Item().PaddingTop(2).Text(customer.ContractTermsText).FontSize(9).LineHeight(1.4f);
                            }
                        });
                        column.Item().PaddingTop(15);
                    }

                    // Footer note
                    column.Item().PaddingTop(20).AlignCenter().Text("Please see Page 2 for Terms and Conditions and Signature Section").FontSize(9).FontColor(QuestPdfColors.Blue.Darken2).Bold();
                    column.Item().PaddingTop(5).AlignCenter().Text($"Document generated on {DateTime.Now:MMMM dd, yyyy 'at' HH:mm}").FontSize(8).FontColor(QuestPdfColors.Grey.Medium);
                });
            });

            // Page 2: Contract Terms and Conditions
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.PageColor(QuestPdfColors.White);
                page.DefaultTextStyle(x => x.FontSize(10));

                // Header with Logo (same as page 1)
                page.Header()
                    .PaddingBottom(10)
                    .Column(headerColumn =>
                    {
                        headerColumn.Item().Row(headerRow =>
                        {
                            var logoBytes = GetLogoBytes();
                            if (logoBytes.Length > 0)
                            {
                                headerRow.ConstantItem(40).PaddingRight(10).Image(logoBytes).FitArea();
                            }
                            
                            headerRow.RelativeItem().Column(companyCol =>
                            {
                                companyCol.Item().Text("BRIGHTENROLL").FontSize(18).Bold().FontColor(QuestPdfColors.Blue.Darken3);
                                companyCol.Item().PaddingTop(2).Text("ENROLLMENT MANAGEMENT SYSTEM").FontSize(11).FontColor(QuestPdfColors.Grey.Darken1);
                                companyCol.Item().PaddingTop(3).Text("SUPER ADMINISTRATOR").FontSize(9).FontColor(QuestPdfColors.Grey.Darken1);
                            });
                            
                            headerRow.RelativeItem().AlignRight().Column(dateCol =>
                            {
                                dateCol.Item().AlignRight().Text($"Date: {DateTime.Now:MMMM dd, yyyy}").FontSize(9);
                                dateCol.Item().AlignRight().Text($"Time: {DateTime.Now:HH:mm}").FontSize(9);
                                dateCol.Item().PaddingTop(2).AlignRight().Text($"Generated by: {generatedBy}").FontSize(9);
                            });
                        });
                        
                        headerColumn.Item().PaddingTop(8).BorderBottom(2).BorderColor(QuestPdfColors.Blue.Darken2);
                    });

                // Footer with page number
                page.Footer()
                    .Height(20)
                    .AlignCenter()
                    .DefaultTextStyle(x => x.FontSize(8).FontColor(QuestPdfColors.Grey.Medium))
                    .Text(x =>
                    {
                        x.Span("Page ");
                        x.CurrentPageNumber();
                        x.Span(" of ");
                        x.TotalPages();
                    });

                // Content: Contract Terms and Conditions
                page.Content().PaddingVertical(10).Column(column =>
                {
                    // Title
                    column.Item().AlignCenter().Text("TERMS AND CONDITIONS").FontSize(16).Bold().FontColor(QuestPdfColors.Blue.Darken3);
                    column.Item().PaddingTop(5).AlignCenter().Text($"Contract Code: {customer.CustomerCode}").FontSize(11).Bold();
                    
                    column.Item().PaddingTop(15);

                    // Preamble
                    column.Item().Text(text =>
                    {
                        text.DefaultTextStyle(style => style.FontSize(10).LineHeight(1.4f));
                        text.Span("THIS AGREEMENT");
                        text.Span(" is entered into on this " + (customer.ContractStartDate?.ToString("dd") ?? "____") + " day of " + (customer.ContractStartDate?.ToString("MMMM, yyyy") ?? "__________, _____") + ", between BRIGHTENROLL ENROLLMENT MANAGEMENT SYSTEM (hereinafter referred to as \"Service Provider\") and " + customer.SchoolName + " (hereinafter referred to as \"Customer\").");
                    });
                    
                    column.Item().PaddingTop(10);

                    // Section 1: Definitions
                    column.Item().Text("1. DEFINITIONS").FontSize(12).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                    column.Item().PaddingTop(5).Background(QuestPdfColors.Grey.Lighten5).Padding(10).Column(defCol =>
                    {
                        defCol.Item().Text("1.1 \"Service\" means the BrightEnroll Enrollment Management System software and related services provided to the Customer.").FontSize(9).LineHeight(1.4f);
                        defCol.Item().PaddingTop(3).Text("1.2 \"Subscription Period\" means the duration of this agreement as specified in Section 3 of this contract.").FontSize(9).LineHeight(1.4f);
                        defCol.Item().PaddingTop(3).Text("1.3 \"Monthly Fee\" means the amount payable by the Customer as specified in Section 2 of this contract.").FontSize(9).LineHeight(1.4f);
                        defCol.Item().PaddingTop(3).Text("1.4 \"Authorized Users\" means employees or agents of the Customer who are authorized to access and use the Service.").FontSize(9).LineHeight(1.4f);
                    });

                    column.Item().PaddingTop(10);

                    // Section 2: Service Provision
                    column.Item().Text("2. SERVICE PROVISION").FontSize(12).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                    column.Item().PaddingTop(5).Background(QuestPdfColors.Grey.Lighten5).Padding(10).Column(serviceCol =>
                    {
                        serviceCol.Item().Text("2.1 The Service Provider agrees to provide the Customer with access to the BrightEnroll Enrollment Management System in accordance with the terms of this Agreement.").FontSize(9).LineHeight(1.4f);
                        serviceCol.Item().PaddingTop(3).Text("2.2 The Service Provider will maintain the Service in good working order and provide technical support during business hours.").FontSize(9).LineHeight(1.4f);
                        serviceCol.Item().PaddingTop(3).Text("2.3 The Service Provider reserves the right to update, modify, or enhance the Service at any time, with reasonable notice to the Customer.").FontSize(9).LineHeight(1.4f);
                        if (!string.IsNullOrWhiteSpace(customer.MaintenanceSchedule))
                        {
                            serviceCol.Item().PaddingTop(3).Text($"2.4 Maintenance Schedule: {customer.MaintenanceSchedule}").FontSize(9).LineHeight(1.4f);
                        }
                        if (!string.IsNullOrWhiteSpace(customer.WarrantyPeriod))
                        {
                            serviceCol.Item().PaddingTop(3).Text($"2.5 Warranty Period: {customer.WarrantyPeriod}").FontSize(9).LineHeight(1.4f);
                        }
                    });

                    column.Item().PaddingTop(10);

                    // Section 3: Payment Terms
                    column.Item().Text("3. PAYMENT TERMS").FontSize(12).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                    column.Item().PaddingTop(5).Background(QuestPdfColors.Grey.Lighten5).Padding(10).Column(paymentCol =>
                    {
                        paymentCol.Item().Text($"3.1 The Customer agrees to pay a monthly fee of ₱{customer.MonthlyFee:N2} for the duration of this Agreement.").FontSize(9).LineHeight(1.4f);
                        paymentCol.Item().PaddingTop(3).Text("3.2 Payment is due on or before the first day of each month. Late payments may incur a penalty fee of 2% per month.").FontSize(9).LineHeight(1.4f);
                        paymentCol.Item().PaddingTop(3).Text("3.3 All fees are exclusive of applicable taxes. The Customer is responsible for any taxes, duties, or fees imposed by any government authority.").FontSize(9).LineHeight(1.4f);
                        if (!string.IsNullOrWhiteSpace(customer.PaymentTerms))
                        {
                            paymentCol.Item().PaddingTop(3).Text($"3.4 Additional Payment Terms: {customer.PaymentTerms}").FontSize(9).LineHeight(1.4f);
                        }
                    });

                    column.Item().PaddingTop(10);

                    // Section 4: Customer Obligations
                    column.Item().Text("4. CUSTOMER OBLIGATIONS").FontSize(12).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                    column.Item().PaddingTop(5).Background(QuestPdfColors.Grey.Lighten5).Padding(10).Column(obligCol =>
                    {
                        obligCol.Item().Text("4.1 The Customer shall use the Service only for lawful purposes and in accordance with this Agreement.").FontSize(9).LineHeight(1.4f);
                        obligCol.Item().PaddingTop(3).Text("4.2 The Customer is responsible for maintaining the confidentiality of all login credentials and ensuring that only Authorized Users access the Service.").FontSize(9).LineHeight(1.4f);
                        obligCol.Item().PaddingTop(3).Text("4.3 The Customer shall not attempt to reverse engineer, decompile, or disassemble the Service or any part thereof.").FontSize(9).LineHeight(1.4f);
                        obligCol.Item().PaddingTop(3).Text("4.4 The Customer shall promptly notify the Service Provider of any unauthorized access or security breach.").FontSize(9).LineHeight(1.4f);
                    });

                    column.Item().PaddingTop(10);

                    // Section 5: Intellectual Property
                    column.Item().Text("5. INTELLECTUAL PROPERTY").FontSize(12).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                    column.Item().PaddingTop(5).Background(QuestPdfColors.Grey.Lighten5).Padding(10).Column(ipCol =>
                    {
                        ipCol.Item().Text("5.1 All intellectual property rights in the Service, including but not limited to software, documentation, and trademarks, remain the exclusive property of the Service Provider.").FontSize(9).LineHeight(1.4f);
                        ipCol.Item().PaddingTop(3).Text("5.2 The Customer is granted a non-exclusive, non-transferable license to use the Service for the duration of this Agreement.").FontSize(9).LineHeight(1.4f);
                        ipCol.Item().PaddingTop(3).Text("5.3 The Customer shall not copy, modify, distribute, or create derivative works based on the Service without prior written consent.").FontSize(9).LineHeight(1.4f);
                    });

                    column.Item().PaddingTop(10);

                    // Section 6: Data Protection and Privacy
                    column.Item().Text("6. DATA PROTECTION AND PRIVACY").FontSize(12).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                    column.Item().PaddingTop(5).Background(QuestPdfColors.Grey.Lighten5).Padding(10).Column(dataCol =>
                    {
                        dataCol.Item().Text("6.1 The Service Provider shall implement reasonable security measures to protect Customer data.").FontSize(9).LineHeight(1.4f);
                        dataCol.Item().PaddingTop(3).Text("6.2 The Customer retains ownership of all data entered into the Service and is responsible for data backup.").FontSize(9).LineHeight(1.4f);
                        dataCol.Item().PaddingTop(3).Text("6.3 The Service Provider will not disclose Customer data to third parties except as required by law or with Customer consent.").FontSize(9).LineHeight(1.4f);
                    });

                    column.Item().PaddingTop(10);

                    // Section 7: Limitation of Liability
                    column.Item().Text("7. LIMITATION OF LIABILITY").FontSize(12).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                    column.Item().PaddingTop(5).Background(QuestPdfColors.Grey.Lighten5).Padding(10).Column(liabilityCol =>
                    {
                        liabilityCol.Item().Text("7.1 The Service Provider shall not be liable for any indirect, incidental, special, or consequential damages arising from the use or inability to use the Service.").FontSize(9).LineHeight(1.4f);
                        liabilityCol.Item().PaddingTop(3).Text("7.2 The total liability of the Service Provider shall not exceed the total fees paid by the Customer in the twelve (12) months preceding the claim.").FontSize(9).LineHeight(1.4f);
                        liabilityCol.Item().PaddingTop(3).Text("7.3 The Service Provider does not guarantee uninterrupted or error-free operation of the Service.").FontSize(9).LineHeight(1.4f);
                    });

                    column.Item().PaddingTop(10);

                    // Section 8: Termination
                    column.Item().Text("8. TERMINATION").FontSize(12).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                    column.Item().PaddingTop(5).Background(QuestPdfColors.Grey.Lighten5).Padding(10).Column(termCol =>
                    {
                        if (!string.IsNullOrWhiteSpace(customer.TerminationClause))
                        {
                            // Use the auto-filled termination clause from the contract template
                            termCol.Item().Text($"8.1 {customer.TerminationClause}").FontSize(9).LineHeight(1.4f);
                        }
                        else
                        {
                            termCol.Item().Text("8.1 Either party may terminate this Agreement with thirty (30) days written notice.").FontSize(9).LineHeight(1.4f);
                        }
                        termCol.Item().PaddingTop(3).Text("8.2 The Service Provider may terminate this Agreement immediately upon breach of payment terms or violation of this Agreement.").FontSize(9).LineHeight(1.4f);
                        termCol.Item().PaddingTop(3).Text("8.3 Upon termination, the Customer's access to the Service will be suspended, and all outstanding fees must be paid.").FontSize(9).LineHeight(1.4f);
                        if (customer.AutoRenewal)
                        {
                            termCol.Item().PaddingTop(3).Text("8.4 This Agreement will automatically renew for successive periods unless either party provides written notice of non-renewal at least thirty (30) days before the end of the current period.").FontSize(9).LineHeight(1.4f);
                        }
                    });
                    
                    column.Item().PaddingTop(10);
                    
                    // Section 8.5: Service Level Agreement (SLA)
                    if (!string.IsNullOrWhiteSpace(customer.SlaDetails))
                    {
                        column.Item().Text("8.5 SERVICE LEVEL AGREEMENT (SLA)").FontSize(12).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                        column.Item().PaddingTop(5).Background(QuestPdfColors.Grey.Lighten5).Padding(10).Column(slaCol =>
                        {
                            slaCol.Item().Text(customer.SlaDetails).FontSize(9).LineHeight(1.4f);
                        });
                        column.Item().PaddingTop(10);
                    }
                    
                    // Section 8.6: Full Contract Terms (if provided)
                    if (!string.IsNullOrWhiteSpace(customer.ContractTermsText))
                    {
                        column.Item().Text("8.6 FULL CONTRACT TERMS").FontSize(12).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                        column.Item().PaddingTop(5).Background(QuestPdfColors.Grey.Lighten5).Padding(10).Column(contractTermsCol =>
                        {
                            contractTermsCol.Item().Text(customer.ContractTermsText).FontSize(9).LineHeight(1.4f);
                        });
                        column.Item().PaddingTop(10);
                    }

                    column.Item().PaddingTop(10);

                    // Section 9: General Provisions
                    column.Item().Text("9. GENERAL PROVISIONS").FontSize(12).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                    column.Item().PaddingTop(5).Background(QuestPdfColors.Grey.Lighten5).Padding(10).Column(generalCol =>
                    {
                        generalCol.Item().Text("9.1 This Agreement constitutes the entire agreement between the parties and supersedes all prior agreements.").FontSize(9).LineHeight(1.4f);
                        generalCol.Item().PaddingTop(3).Text("9.2 Any modification to this Agreement must be in writing and signed by both parties.").FontSize(9).LineHeight(1.4f);
                        generalCol.Item().PaddingTop(3).Text("9.3 If any provision of this Agreement is found to be invalid, the remaining provisions shall remain in full force and effect.").FontSize(9).LineHeight(1.4f);
                        generalCol.Item().PaddingTop(3).Text("9.4 This Agreement shall be governed by the laws of the Philippines.").FontSize(9).LineHeight(1.4f);
                        generalCol.Item().PaddingTop(3).Text("9.5 Any disputes arising from this Agreement shall be resolved through amicable negotiation, and if unsuccessful, through arbitration in accordance with Philippine law.").FontSize(9).LineHeight(1.4f);
                    });

                    column.Item().PaddingTop(20);

                    // Signature Section
                    column.Item().BorderTop(2).BorderColor(QuestPdfColors.Blue.Darken2).PaddingTop(15).Text("IN WITNESS WHEREOF, the parties have executed this Agreement as of the date first written above.").FontSize(10).Bold().AlignCenter();
                    
                    column.Item().PaddingTop(30).Row(signatureRow =>
                    {
                        // Customer Signature
                        signatureRow.RelativeItem().Column(customerSigCol =>
                        {
                            customerSigCol.Item().Text("CUSTOMER").FontSize(10).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                            customerSigCol.Item().PaddingTop(40).BorderBottom(1).BorderColor(QuestPdfColors.Black);
                            customerSigCol.Item().PaddingTop(5).Text(customer.SchoolName ?? "").FontSize(9).Bold();
                            customerSigCol.Item().Text("(Company/School Name)").FontSize(8).FontColor(QuestPdfColors.Grey.Medium);
                            customerSigCol.Item().PaddingTop(10).BorderBottom(1).BorderColor(QuestPdfColors.Black);
                            customerSigCol.Item().PaddingTop(5).Text(customer.ContactPerson ?? "").FontSize(9);
                            customerSigCol.Item().Text("(Authorized Signatory)").FontSize(8).FontColor(QuestPdfColors.Grey.Medium);
                            customerSigCol.Item().PaddingTop(5).Text("Print Name: _________________________").FontSize(8);
                            customerSigCol.Item().Text("Position: _________________________").FontSize(8);
                        });
                        
                        signatureRow.ConstantItem(50);
                        
                        // Service Provider Signature
                        signatureRow.RelativeItem().Column(providerSigCol =>
                        {
                            providerSigCol.Item().Text("SERVICE PROVIDER").FontSize(10).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                            providerSigCol.Item().PaddingTop(40).BorderBottom(1).BorderColor(QuestPdfColors.Black);
                            providerSigCol.Item().PaddingTop(5).Text("BRIGHTENROLL ENROLLMENT MANAGEMENT SYSTEM").FontSize(9).Bold();
                            providerSigCol.Item().Text("(Company Name)").FontSize(8).FontColor(QuestPdfColors.Grey.Medium);
                            providerSigCol.Item().PaddingTop(10).BorderBottom(1).BorderColor(QuestPdfColors.Black);
                            providerSigCol.Item().PaddingTop(5).Text(generatedBy).FontSize(9);
                            providerSigCol.Item().Text("(Authorized Representative)").FontSize(8).FontColor(QuestPdfColors.Grey.Medium);
                            providerSigCol.Item().PaddingTop(5).Text("Print Name: _________________________").FontSize(8);
                            providerSigCol.Item().Text("Position: _________________________").FontSize(8);
                        });
                    });

                    column.Item().PaddingTop(20).Row(stampRow =>
                    {
                        stampRow.RelativeItem().Column(stampCol =>
                        {
                            stampCol.Item().Text("CUSTOMER STAMP/SEAL").FontSize(9).FontColor(QuestPdfColors.Grey.Medium).AlignCenter();
                            stampCol.Item().PaddingTop(30).Border(1).BorderColor(QuestPdfColors.Grey.Medium).Height(60).Width(60).AlignCenter();
                        });
                        
                        stampRow.ConstantItem(50);
                        
                        stampRow.RelativeItem().Column(stampCol =>
                        {
                            stampCol.Item().Text("SERVICE PROVIDER STAMP/SEAL").FontSize(9).FontColor(QuestPdfColors.Grey.Medium).AlignCenter();
                            stampCol.Item().PaddingTop(30).Border(1).BorderColor(QuestPdfColors.Grey.Medium).Height(60).Width(60).AlignCenter();
                        });
                    });

                    column.Item().PaddingTop(20).AlignCenter().Text($"Document generated on {DateTime.Now:MMMM dd, yyyy 'at' HH:mm}").FontSize(8).FontColor(QuestPdfColors.Grey.Medium);
                });
            });
        }).GeneratePdf();
    }
}
