using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace BrightEnroll_DES.Services.QuestPDF;

public class PaymentReceiptPdfGenerator
{
    private byte[]? _logoBytes;

    private byte[] GetLogoBytes()
    {
        if (_logoBytes != null) return _logoBytes;
        
        var logoPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "reportPDF.png");
        if (File.Exists(logoPath))
        {
            _logoBytes = File.ReadAllBytes(logoPath);
        }
        return _logoBytes ?? Array.Empty<byte>();
    }

    public byte[] GeneratePaymentReceipt(ReceiptData receiptData)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.PageColor(global::QuestPDF.Helpers.Colors.White);
                page.DefaultTextStyle(x => x.FontSize(10));

                // Enhanced Header - Two Column Layout
                page.Header()
                    .PaddingBottom(10)
                    .Column(headerColumn =>
                    {
                        // Top Row: Logo/Company Info on Left, Department/Date/Time on Right (matched heights)
                        headerColumn.Item().Height(50).Row(headerRow =>
                        {
                            // Left Side: Logo and Company Information
                            headerRow.RelativeItem(2).Row(leftRow =>
                            {
                                var logoBytes = GetLogoBytes();
                                if (logoBytes != null && logoBytes.Length > 0)
                                {
                                    leftRow.ConstantItem(50).Height(50).Image(logoBytes).FitArea();
                                }
                                
                                leftRow.RelativeItem().PaddingLeft(10).Column(companyCol =>
                                {
                                    companyCol.Item().Text("BRIGHTENROLL").FontSize(16).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                    companyCol.Item().PaddingTop(2).Text("ENROLLMENT MANAGEMENT SYSTEM").FontSize(10).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    companyCol.Item().PaddingTop(3).Text("Elementary School").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                });
                            });

                            // Right Side: Only Department, Date, and Time (matched height)
                            headerRow.RelativeItem(1).AlignRight().Column(detailsCol =>
                            {
                                detailsCol.Item().Text("FINANCE DEPARTMENT").FontSize(10).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                                detailsCol.Item().PaddingTop(3).Row(row =>
                                {
                                    row.RelativeItem().Text("Date:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    row.RelativeItem().Text(receiptData.PaymentDate.ToString("MMMM dd, yyyy")).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                                detailsCol.Item().PaddingTop(2).Row(row =>
                                {
                                    row.RelativeItem().Text("Time:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    row.RelativeItem().Text(receiptData.PaymentDate.ToString("hh:mm tt")).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                            });
                        });
                        
                        // Border line below header row
                        headerColumn.Item().PaddingTop(8).BorderBottom(1).BorderColor(global::QuestPDF.Helpers.Colors.Black);
                        
                        // Report Details Below the Line: 2 Columns - Document Type/Receipt # on left, Generated By on right
                        headerColumn.Item().PaddingTop(8).Row(detailsRow =>
                        {
                            // Column 1: Document Type and Receipt # (stacked rows)
                            detailsRow.RelativeItem().Column(leftDetailsCol =>
                            {
                                leftDetailsCol.Item().Row(row =>
                                {
                                    row.ConstantItem(75).Text("Document Type:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    row.RelativeItem().Text("Official Receipt").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                                leftDetailsCol.Item().PaddingTop(2).Row(row =>
                                {
                                    row.ConstantItem(75).Text("Receipt #:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    row.RelativeItem().Text(receiptData.OrNumber).FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                            });
                            
                            // Column 2: Generated By
                            detailsRow.RelativeItem().AlignRight().Column(rightDetailsCol =>
                            {
                                rightDetailsCol.Item().Row(row =>
                                {
                                    row.ConstantItem(70).Text("Generated By:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    rightDetailsCol.Item().Text(receiptData.ProcessedBy).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                            });
                        });
                    });

                // Content
                page.Content()
                    .PaddingVertical(1, Unit.Centimetre)
                    .Column(column =>
                    {
                        // Receipt Number and Date
                        column.Item().Row(row =>
                        {
                            row.RelativeItem().Column(col =>
                            {
                                col.Item().Text("Official Receipt Number").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Medium);
                                col.Item().PaddingTop(2).Text(receiptData.OrNumber).FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                            });
                            
                            row.RelativeItem().AlignRight().Column(col =>
                            {
                                col.Item().Text("Date").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Medium);
                                col.Item().PaddingTop(2).Text(receiptData.PaymentDate.ToString("MMMM dd, yyyy")).FontSize(11).Bold();
                                col.Item().Text(receiptData.PaymentDate.ToString("hh:mm tt")).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                            });
                        });

                        column.Item().PaddingTop(15).BorderTop(1).BorderColor(global::QuestPDF.Helpers.Colors.Grey.Lighten2).PaddingTop(10);

                        // Student Information
                        column.Item().Column(studentCol =>
                        {
                            studentCol.Item().Text("Student Information").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Medium);
                            studentCol.Item().PaddingTop(3).Text(receiptData.StudentName).FontSize(11).Bold();
                            studentCol.Item().Text($"Student ID: {receiptData.StudentId}").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                            studentCol.Item().Text($"Grade Level: {receiptData.GradeLevel}").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                        });

                        column.Item().PaddingTop(15).BorderTop(1).BorderColor(global::QuestPDF.Helpers.Colors.Grey.Lighten2).PaddingTop(10);

                        // Payment Details
                        column.Item().Column(paymentCol =>
                        {
                            paymentCol.Item().Text("Payment Details").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Medium);
                            paymentCol.Item().PaddingTop(5).Row(row =>
                            {
                                row.RelativeItem().Text("Payment Amount:").FontSize(9);
                                row.RelativeItem().AlignRight().Text($"₱{receiptData.PaymentAmount:N2}").FontSize(9).Bold();
                            });
                            paymentCol.Item().PaddingTop(3).Row(row =>
                            {
                                row.RelativeItem().Text("Payment Method:").FontSize(9);
                                row.RelativeItem().AlignRight().Text(receiptData.PaymentMethod).FontSize(9).Bold();
                            });
                        });

                        column.Item().PaddingTop(15).BorderTop(2).BorderColor(global::QuestPDF.Helpers.Colors.Grey.Medium).PaddingTop(10);

                        // Summary of Charges
                        column.Item().Column(summaryCol =>
                        {
                            summaryCol.Item().Row(row =>
                            {
                                row.RelativeItem().Text("Total Assessment:").FontSize(9);
                                row.RelativeItem().AlignRight().Text($"₱{receiptData.TotalFee:N2}").FontSize(9).Bold();
                            });
                            summaryCol.Item().PaddingTop(5).Row(row =>
                            {
                                row.RelativeItem().Text("Previous Payments:").FontSize(9);
                                row.RelativeItem().AlignRight().Text($"₱{receiptData.PreviousPaid:N2}").FontSize(9).Bold();
                            });
                            summaryCol.Item().PaddingTop(5).Row(row =>
                            {
                                row.RelativeItem().Text("This Payment:").FontSize(9);
                                row.RelativeItem().AlignRight().Text($"₱{receiptData.PaymentAmount:N2}").FontSize(9).Bold();
                            });
                            
                            summaryCol.Item().PaddingTop(10).BorderTop(1).BorderColor(global::QuestPDF.Helpers.Colors.Grey.Lighten2).PaddingTop(5);
                            
                            summaryCol.Item().Row(row =>
                            {
                                row.RelativeItem().Text("Total Paid:").FontSize(11).Bold();
                                row.RelativeItem().AlignRight().Text($"₱{receiptData.TotalPaid:N2}").FontSize(11).Bold();
                            });
                            
                            summaryCol.Item().PaddingTop(5).Row(row =>
                            {
                                row.RelativeItem().Text("Remaining Balance:").FontSize(11).Bold();
                                row.RelativeItem().AlignRight().Text($"₱{receiptData.Balance:N2}").FontSize(11).Bold()
                                    .FontColor(receiptData.Balance > 0 ? global::QuestPDF.Helpers.Colors.Red.Darken2 : global::QuestPDF.Helpers.Colors.Green.Darken2);
                            });
                        });

                        // Footer Message
                        column.Item().PaddingTop(20).BorderTop(2).BorderColor(global::QuestPDF.Helpers.Colors.Grey.Medium).PaddingTop(15)
                            .AlignCenter().Column(footerCol =>
                            {
                                footerCol.Item().Text("Thank you for your payment!").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Medium);
                                footerCol.Item().PaddingTop(3).Text("This is an official receipt. Please keep this for your records.").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                footerCol.Item().PaddingTop(10).Text($"Processed by: {receiptData.ProcessedBy}").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                            });
                    });
            });
        }).GeneratePdf();
    }

    public class ReceiptData
    {
        public string OrNumber { get; set; } = string.Empty;
        public DateTime PaymentDate { get; set; }
        public string StudentId { get; set; } = string.Empty;
        public string StudentName { get; set; } = string.Empty;
        public string GradeLevel { get; set; } = string.Empty;
        public decimal PaymentAmount { get; set; }
        public string PaymentMethod { get; set; } = string.Empty;
        public decimal TotalFee { get; set; }
        public decimal PreviousPaid { get; set; }
        public decimal TotalPaid { get; set; }
        public decimal Balance { get; set; }
        public string ProcessedBy { get; set; } = string.Empty;
    }
}

