using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace BrightEnroll_DES.Services.QuestPDF;

/// <summary>
/// Generates a payment slip PDF for students with "For Payment" status.
/// This slip is given to parents to present to the cashier for downpayment.
/// </summary>
public class PaymentSlipPdfGenerator
{
    private byte[]? _logoBytes;

    private byte[] GetLogoBytes()
    {
        if (_logoBytes != null) return _logoBytes;
        
        var logoPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "reportPDF.png");
        if (File.Exists(logoPath))
        {
            _logoBytes = File.ReadAllBytes(logoPath);
        }
        return _logoBytes ?? Array.Empty<byte>();
    }

    public byte[] GeneratePaymentSlip(PaymentSlipData slipData)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.PageColor(global::QuestPDF.Helpers.Colors.White);
                page.DefaultTextStyle(x => x.FontSize(10));

                // Enhanced Header - Two Column Layout
                page.Header()
                    .PaddingBottom(10)
                    .Column(headerColumn =>
                    {
                        // Top Row: Logo/Company Info on Left, Department/Date/Time on Right (matched heights)
                        headerColumn.Item().Height(50).Row(headerRow =>
                        {
                            // Left Side: Logo and Company Information
                            headerRow.RelativeItem(2).Row(leftRow =>
                            {
                                var logoBytes = GetLogoBytes();
                                if (logoBytes != null && logoBytes.Length > 0)
                                {
                                    leftRow.ConstantItem(50).Height(50).Image(logoBytes).FitArea();
                                }
                                
                                leftRow.RelativeItem().PaddingLeft(10).Column(companyCol =>
                                {
                                    companyCol.Item().Text("BRIGHTENROLL").FontSize(16).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                    companyCol.Item().PaddingTop(2).Text("ENROLLMENT MANAGEMENT SYSTEM").FontSize(10).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    companyCol.Item().PaddingTop(3).Text("Elementary School").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                });
                            });

                            // Right Side: Only Department, Date, and Time (matched height)
                            headerRow.RelativeItem(1).AlignRight().Column(detailsCol =>
                            {
                                detailsCol.Item().Text("FINANCE DEPARTMENT").FontSize(10).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                                detailsCol.Item().PaddingTop(3).Row(row =>
                                {
                                    row.RelativeItem().Text("Date:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    row.RelativeItem().Text(slipData.DateGenerated.ToString("MMMM dd, yyyy")).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                                detailsCol.Item().PaddingTop(2).Row(row =>
                                {
                                    row.RelativeItem().Text("Time:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    row.RelativeItem().Text(slipData.DateGenerated.ToString("hh:mm tt")).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                            });
                        });
                        
                        // Border line below header row
                        headerColumn.Item().PaddingTop(8).BorderBottom(1).BorderColor(global::QuestPDF.Helpers.Colors.Black);
                        
                        // Report Details Below the Line: 2 Columns - Document Type/Student ID on left, Generated By on right
                        headerColumn.Item().PaddingTop(8).Row(detailsRow =>
                        {
                            // Column 1: Document Type and Student ID (stacked rows)
                            detailsRow.RelativeItem().Column(leftDetailsCol =>
                            {
                                leftDetailsCol.Item().Row(row =>
                                {
                                    row.ConstantItem(75).Text("Document Type:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    row.RelativeItem().Text("Payment Slip").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                                leftDetailsCol.Item().PaddingTop(2).Row(row =>
                                {
                                    row.ConstantItem(75).Text("Student ID:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    row.RelativeItem().Text(slipData.StudentId).FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                            });
                            
                            // Column 2: Generated By
                            detailsRow.RelativeItem().AlignRight().Column(rightDetailsCol =>
                            {
                                rightDetailsCol.Item().Row(row =>
                                {
                                    row.ConstantItem(70).Text("Generated By:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    rightDetailsCol.Item().Text("System").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black); // Payment slips are system-generated
                                });
                            });
                        });
                    });

                // Content
                page.Content()
                    .PaddingVertical(1, Unit.Centimetre)
                    .Column(column =>
                    {
                        // Date
                        column.Item().AlignRight().Text($"Date: {slipData.DateGenerated:MMMM dd, yyyy}").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);

                        column.Item().PaddingTop(15).BorderTop(1).BorderColor(global::QuestPDF.Helpers.Colors.Grey.Lighten2).PaddingTop(10);

                        // Student Information Section
                        column.Item().Column(studentCol =>
                        {
                            studentCol.Item().Text("STUDENT INFORMATION").FontSize(10).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                            
                            studentCol.Item().PaddingTop(8).Row(row =>
                            {
                                row.RelativeItem(2).Text("Student ID:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                row.RelativeItem(3).Text(slipData.StudentId).FontSize(11).Bold();
                            });

                            studentCol.Item().PaddingTop(5).Row(row =>
                            {
                                row.RelativeItem(2).Text("Student Name:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                row.RelativeItem(3).Text(slipData.StudentName).FontSize(11).Bold();
                            });

                            studentCol.Item().PaddingTop(5).Row(row =>
                            {
                                row.RelativeItem(2).Text("Grade Level:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                row.RelativeItem(3).Text(slipData.GradeLevel).FontSize(11).Bold();
                            });

                            studentCol.Item().PaddingTop(5).Row(row =>
                            {
                                row.RelativeItem(2).Text("School Year:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                row.RelativeItem(3).Text(slipData.SchoolYear).FontSize(11).Bold();
                            });

                            studentCol.Item().PaddingTop(5).Row(row =>
                            {
                                row.RelativeItem(2).Text("Status:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                row.RelativeItem(3).Text(slipData.Status).FontSize(11).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken2);
                            });
                        });

                        column.Item().PaddingTop(20).BorderTop(1).BorderColor(global::QuestPDF.Helpers.Colors.Grey.Lighten2).PaddingTop(10);

                        // Instructions Section
                        column.Item().Column(instructionsCol =>
                        {
                            instructionsCol.Item().Text("INSTRUCTIONS FOR CASHIER").FontSize(10).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                            
                            instructionsCol.Item().PaddingTop(8).Text("1. Verify the student information above.").FontSize(9);
                            instructionsCol.Item().PaddingTop(3).Text("2. Process the downpayment payment.").FontSize(9);
                            instructionsCol.Item().PaddingTop(3).Text("3. Update the student's payment status in the system.").FontSize(9);
                            instructionsCol.Item().PaddingTop(3).Text("4. Provide the official receipt to the parent/guardian.").FontSize(9);
                        });

                        column.Item().PaddingTop(20).BorderTop(1).BorderColor(global::QuestPDF.Helpers.Colors.Grey.Lighten2).PaddingTop(10);

                        // Footer Message
                        column.Item().AlignCenter().Column(footerCol =>
                        {
                            footerCol.Item().Text("Please present this slip to the cashier for payment processing.").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Medium);
                            footerCol.Item().PaddingTop(5).Text("This document is valid for payment processing only.").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                        });
                    });
            });
        }).GeneratePdf();
    }

    public class PaymentSlipData
    {
        public string StudentId { get; set; } = string.Empty;
        public string StudentName { get; set; } = string.Empty;
        public string GradeLevel { get; set; } = string.Empty;
        public string SchoolYear { get; set; } = string.Empty;
        public string Status { get; set; } = string.Empty;
        public DateTime DateGenerated { get; set; } = DateTime.Now;
    }
}

