using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.IO;

namespace BrightEnroll_DES.Services.QuestPDF;

public class PayrollReportPdfGenerator
{
    private byte[]? _logoBytes;

    private byte[] GetLogoBytes()
    {
        if (_logoBytes != null) return _logoBytes;
        
        var logoPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "reportPDF.png");
        if (File.Exists(logoPath))
        {
            _logoBytes = File.ReadAllBytes(logoPath);
        }
        return _logoBytes ?? Array.Empty<byte>();
    }

    public byte[] GeneratePayrollReport(
        List<PayrollReportDataItem> data,
        string reportType,
        string generatedBy,
        string userRole,
        DateTime? dateFrom = null,
        DateTime? dateTo = null,
        string? statusFilter = null,
        string? schoolYearFilter = null,
        string? employeeFilter = null,
        Services.Business.Payroll.PayrollFinancialInsightsService.FinancialInsights? financialInsights = null)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(1.5f, Unit.Centimetre);
                page.PageColor(global::QuestPDF.Helpers.Colors.White);
                page.DefaultTextStyle(x => x.FontSize(10));

                // Enhanced Header - Two Column Layout
                page.Header()
                    .PaddingBottom(10)
                    .Column(headerColumn =>
                    {
                        // Top Row: Logo/Company Info on Left, Department/Date/Time on Right (matched heights)
                        headerColumn.Item().Height(50).Row(headerRow =>
                        {
                            // Left Side: Logo and Company Information
                            headerRow.RelativeItem(2).Row(leftRow =>
                            {
                                var logoBytes = GetLogoBytes();
                                if (logoBytes.Length > 0)
                                {
                                    leftRow.ConstantItem(50).Height(50).Image(logoBytes).FitArea();
                                }
                                
                                leftRow.RelativeItem().PaddingLeft(10).Column(companyCol =>
                                {
                                    companyCol.Item().Text("BRIGHTENROLL").FontSize(16).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                    companyCol.Item().PaddingTop(2).Text("ENROLLMENT MANAGEMENT SYSTEM").FontSize(10).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    companyCol.Item().PaddingTop(3).Text("Elementary School").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                });
                            });

                            // Right Side: Only Department, Date, and Time (matched height)
                            headerRow.RelativeItem(1).AlignRight().Column(detailsCol =>
                            {
                                detailsCol.Item().Text("PAYROLL DEPARTMENT").FontSize(10).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                                detailsCol.Item().PaddingTop(3).Row(row =>
                                {
                                    row.RelativeItem().Text("Date:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    row.RelativeItem().Text(DateTime.Now.ToString("MMMM dd, yyyy")).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                                detailsCol.Item().PaddingTop(2).Row(row =>
                                {
                                    row.RelativeItem().Text("Time:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    row.RelativeItem().Text(DateTime.Now.ToString("hh:mm tt")).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                            });
                        });
                        
                        // Border line below header row
                        headerColumn.Item().PaddingTop(8).BorderBottom(1).BorderColor(global::QuestPDF.Helpers.Colors.Black);
                        
                        // Report Details Below the Line: 2 Columns - Report Type/Period on left, Generated By on right
                        headerColumn.Item().PaddingTop(8).Row(detailsRow =>
                        {
                            // Column 1: Report Type and Period (stacked rows)
                            detailsRow.RelativeItem().Column(leftDetailsCol =>
                            {
                                leftDetailsCol.Item().Row(row =>
                                {
                                    row.ConstantItem(60).Text("Report Type:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    row.RelativeItem().Text(GetReportTitle(reportType)).FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                                if (dateFrom.HasValue && dateTo.HasValue)
                                {
                                    leftDetailsCol.Item().PaddingTop(2).Row(row =>
                                    {
                                        row.ConstantItem(60).Text("Period:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                        row.RelativeItem().Text($"{dateFrom.Value:MMM dd} - {dateTo.Value:MMM dd, yyyy}").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    });
                                }
                            });
                            
                            // Column 2: Generated By
                            detailsRow.RelativeItem().AlignRight().Column(rightDetailsCol =>
                            {
                                rightDetailsCol.Item().Row(row =>
                                {
                                    row.ConstantItem(70).Text("Generated By:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    row.RelativeItem().Text($"{generatedBy} ({userRole})").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                            });
                        });
                    });

                // Content
                page.Content()
                    .PaddingVertical(10)
                    .Column(column =>
                    {
                        // Report Title
                        column.Item().Column(titleCol =>
                        {
                            titleCol.Item().Text(GetReportTitle(reportType)).FontSize(20).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                            titleCol.Item().PaddingTop(2).Text("Payroll Transaction Report").FontSize(12).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                        });

                        // Report Information Box
                        column.Item().PaddingTop(10).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Grey.Lighten2)
                            .Padding(12).Background(global::QuestPDF.Helpers.Colors.White)
                            .Column(infoCol =>
                            {
                                infoCol.Item().Row(row =>
                                {
                                    row.RelativeItem().Column(col =>
                                    {
                                        col.Item().Text("Generated By:").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                        col.Item().PaddingTop(1).Text($"{generatedBy} ({userRole})").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken2);
                                    });
                                    row.RelativeItem().Column(col =>
                                    {
                                        col.Item().Text("Generated On:").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                        col.Item().PaddingTop(1).Text(DateTime.Now.ToString("MMMM dd, yyyy 'at' hh:mm tt")).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                    });
                                });

                                infoCol.Item().PaddingTop(8).Row(row =>
                                {
                                    row.RelativeItem().Column(col =>
                                    {
                                        col.Item().Text("Date Range:").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                        var dateRange = dateFrom.HasValue && dateTo.HasValue
                                            ? $"{dateFrom.Value:MMMM dd, yyyy} to {dateTo.Value:MMMM dd, yyyy}"
                                            : "All Dates";
                                        col.Item().PaddingTop(1).Text(dateRange).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                    });
                                    row.RelativeItem().Column(col =>
                                    {
                                        col.Item().Text("Total Records:").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                        col.Item().PaddingTop(1).Text(data.Count.ToString()).FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken2);
                                    });
                                });

                                if (!string.IsNullOrEmpty(statusFilter))
                                {
                                    infoCol.Item().PaddingTop(5).Row(row =>
                                    {
                                        row.RelativeItem().Column(col =>
                                        {
                                            col.Item().Text("Status Filter:").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                            col.Item().PaddingTop(1).Text(statusFilter).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                        });
                                    });
                                }

                                if (!string.IsNullOrEmpty(schoolYearFilter))
                                {
                                    infoCol.Item().PaddingTop(5).Row(row =>
                                    {
                                        row.RelativeItem().Column(col =>
                                        {
                                            col.Item().Text("School Year:").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                            col.Item().PaddingTop(1).Text(schoolYearFilter).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                        });
                                    });
                                }
                            });

                        // Financial Summary - Simplified
                        var paidData = data.Where(d => d.Status == "Paid").ToList();
                        var cancelledData = data.Where(d => d.Status == "Cancelled").ToList();
                        var pendingData = data.Where(d => d.Status == "Pending").ToList();
                        var totalCount = data.Count;
                        var paidCount = paidData.Count;
                        var cancelledCount = cancelledData.Count;
                        var pendingCount = pendingData.Count;
                        var paidPercentage = totalCount > 0 ? (paidCount * 100.0 / totalCount) : 0;
                        var cancelledPercentage = totalCount > 0 ? (cancelledCount * 100.0 / totalCount) : 0;
                        var totalPaidNetPay = paidData.Sum(d => d.NetSalary);
                        var totalPaidGrossPay = paidData.Sum(d => d.GrossSalary);
                        var totalPaidDeductions = paidData.Sum(d => d.TotalDeductions);
                        var totalCompanyContributions = paidData.Sum(d => d.TotalCompanyContribution);
                        var totalCompanyExpense = totalPaidGrossPay + totalCompanyContributions;
                        
                        column.Item().PaddingTop(15).Row(row =>
                        {
                            row.RelativeItem().Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Green.Lighten2)
                                .Padding(8).Background(global::QuestPDF.Helpers.Colors.Green.Lighten4)
                                .Column(card =>
                                {
                                    card.Item().Text("Amount Paid").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                    card.Item().PaddingTop(1).Text($"₱{totalPaidNetPay:N2}").FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Green.Darken2);
                                    card.Item().PaddingTop(1).Text($"{paidCount} transaction(s)").FontSize(7).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                });
                            
                            row.RelativeItem().PaddingLeft(6).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Blue.Lighten2)
                                .Padding(8).Background(global::QuestPDF.Helpers.Colors.Blue.Lighten4)
                                .Column(card =>
                                {
                                    card.Item().Text("Gross Payroll").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                    card.Item().PaddingTop(1).Text($"₱{totalPaidGrossPay:N2}").FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken2);
                                    card.Item().PaddingTop(1).Text("Before deductions").FontSize(7).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                });
                            
                            row.RelativeItem().PaddingLeft(6).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Orange.Lighten2)
                                .Padding(8).Background(global::QuestPDF.Helpers.Colors.Orange.Lighten4)
                                .Column(card =>
                                {
                                    card.Item().Text("Total Deductions").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                    card.Item().PaddingTop(1).Text($"₱{totalPaidDeductions:N2}").FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Orange.Darken2);
                                    card.Item().PaddingTop(1).Text("SSS, PhilHealth, Tax").FontSize(7).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                });
                        });
                        
                        // Company Contributions and Total Expense Row
                        column.Item().PaddingTop(8).Row(row =>
                        {
                            row.RelativeItem().Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Purple.Lighten2)
                                .Padding(8).Background(global::QuestPDF.Helpers.Colors.Purple.Lighten4)
                                .Column(card =>
                                {
                                    card.Item().Text("Company Contributions").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                    card.Item().PaddingTop(1).Text($"₱{totalCompanyContributions:N2}").FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Purple.Darken2);
                                    card.Item().PaddingTop(1).Text("SSS, PhilHealth, Pag-IBIG").FontSize(7).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                });
                            
                            row.RelativeItem().PaddingLeft(6).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Red.Lighten2)
                                .Padding(8).Background(global::QuestPDF.Helpers.Colors.Red.Lighten4)
                                .Column(card =>
                                {
                                    card.Item().Text("Total Company Expense").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                    card.Item().PaddingTop(1).Text($"₱{totalCompanyExpense:N2}").FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Red.Darken2);
                                    card.Item().PaddingTop(1).Text("Gross + Contributions").FontSize(7).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                });
                        });
                        
                        // Financial Insights & Recommendations Section
                        column.Item().PaddingTop(12).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Grey.Lighten2)
                            .Padding(10).Background(global::QuestPDF.Helpers.Colors.White)
                            .Column(insightsCol =>
                            {
                                insightsCol.Item().Text("Financial Insights & Recommendations").FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken3);
                                
                                if (financialInsights != null && (financialInsights.Insights.Any() || financialInsights.Recommendations.Any()))
                                {
                                    // Financial Insights
                                    if (financialInsights.Insights.Any())
                                    {
                                        insightsCol.Item().PaddingTop(5).Text("Financial Insights:").FontSize(12).Bold().FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken3);
                                        foreach (var insight in financialInsights.Insights)
                                        {
                                            insightsCol.Item().PaddingTop(2).Text($"  • {insight}").FontSize(11).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                        }
                                    }
                                    
                                    // Recommendations
                                    if (financialInsights.Recommendations.Any())
                                    {
                                        insightsCol.Item().PaddingTop(5).Text("Recommendations:").FontSize(12).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                        foreach (var recommendation in financialInsights.Recommendations)
                                        {
                                            insightsCol.Item().PaddingTop(2).Text($"  • {recommendation}").FontSize(11).FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken2);
                                        }
                                    }
                                }
                                else
                                {
                                    // Fallback to basic financial info if insights not available
                                    insightsCol.Item().PaddingTop(4).Text($"• Total Company Expense: ₱{totalCompanyExpense:N2} (Gross Payroll: ₱{totalPaidGrossPay:N2} + Company Contributions: ₱{totalCompanyContributions:N2})").FontSize(11).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                    insightsCol.Item().PaddingTop(2).Text($"• Company Contributions: ₱{totalCompanyContributions:N2} in employer contributions (SSS, PhilHealth, Pag-IBIG) for paid transactions.").FontSize(11).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                    insightsCol.Item().PaddingTop(2).Text($"• Net Pay Disbursed: ₱{totalPaidNetPay:N2} successfully disbursed to employees.").FontSize(11).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                }
                            });
                        

                        // Data Tables - Separated for Audit Trail
                        if (reportType == "AuditTrail")
                        {
                            
                            // Paid Transactions Table
                            if (paidData.Any())
                            {
                                column.Item().PaddingTop(15).Text($"Paid Transactions ({paidData.Count})").FontSize(12).Bold().FontColor(global::QuestPDF.Helpers.Colors.Green.Darken2);
                                column.Item().PaddingTop(5).Table(table =>
                                {
                                    table.ColumnsDefinition(columns =>
                                    {
                                        columns.ConstantColumn(50); // Transaction ID
                                        columns.RelativeColumn(2.5f);  // Employee
                                        columns.RelativeColumn(1.5f); // Net Pay
                                        columns.RelativeColumn(2f); // Processed By
                                        columns.RelativeColumn(1.5f); // Date
                                    });
                                    
                                    // Header - White background with colored text and separator line
                                    table.Header(header =>
                                    {
                                        header.Cell().Element(HeaderCellStyle).Text("ID").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignLeft();
                                        header.Cell().Element(HeaderCellStyle).Text("Employee").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignLeft();
                                        header.Cell().Element(HeaderCellStyle).Text("Net Pay").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignRight();
                                        header.Cell().Element(HeaderCellStyle).Text("Processed By").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignLeft();
                                        header.Cell().Element(HeaderCellStyle).Text("Date").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignLeft();
                                    });
                                    
                                    // Rows
                                    int rowIndex = 1;
                                    foreach (var item in paidData)
                                    {
                                        table.Cell().Element(CellStyle).AlignLeft().Text($"Row {rowIndex}: #{item.TransactionId}").FontSize(8);
                                        table.Cell().Element(CellStyle).AlignLeft().Text(item.EmployeeName).FontSize(8);
                                        table.Cell().Element(CellStyle).AlignRight().Text($"₱{item.NetSalary:N2}").FontSize(8).Bold().FontColor(global::QuestPDF.Helpers.Colors.Green.Darken2);
                                        table.Cell().Element(CellStyle).AlignLeft().Column(cellCol =>
                                        {
                                            cellCol.Item().Text(item.ProcessedByName ?? item.ApprovedByName ?? "N/A").FontSize(8);
                                            if (!string.IsNullOrEmpty(item.ProcessedByRole ?? item.ApprovedByRole))
                                            {
                                                cellCol.Item().Text(item.ProcessedByRole ?? item.ApprovedByRole).FontSize(6).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                            }
                                        });
                                        table.Cell().Element(CellStyle).AlignLeft().Text(item.CreatedAt.ToString("MMM dd, yyyy")).FontSize(8);
                                        rowIndex++;
                                    }
                                });
                            }
                            
                            // Cancelled Transactions Table
                            if (cancelledData.Any())
                            {
                                column.Item().PaddingTop(15).Text($"Cancelled Transactions ({cancelledData.Count})").FontSize(12).Bold().FontColor(global::QuestPDF.Helpers.Colors.Red.Darken2);
                                column.Item().PaddingTop(5).Table(table =>
                                {
                                    table.ColumnsDefinition(columns =>
                                    {
                                        columns.ConstantColumn(50); // Transaction ID
                                        columns.RelativeColumn(2.5f);  // Employee
                                        columns.RelativeColumn(1.5f); // Net Pay
                                        columns.RelativeColumn(2f); // Cancelled By
                                        columns.RelativeColumn(1.5f); // Date
                                    });
                                    
                                    // Header - White background with colored text and separator line
                                    table.Header(header =>
                                    {
                                        header.Cell().Element(HeaderCellStyle).Text("ID").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignLeft();
                                        header.Cell().Element(HeaderCellStyle).Text("Employee").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignLeft();
                                        header.Cell().Element(HeaderCellStyle).Text("Net Pay").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignRight();
                                        header.Cell().Element(HeaderCellStyle).Text("Cancelled By").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignLeft();
                                        header.Cell().Element(HeaderCellStyle).Text("Date").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignLeft();
                                    });
                                    
                                    // Rows
                                    int rowIndex = 1;
                                    foreach (var item in cancelledData)
                                    {
                                        table.Cell().Element(CellStyle).AlignLeft().Text($"Row {rowIndex}: #{item.TransactionId}").FontSize(8);
                                        table.Cell().Element(CellStyle).AlignLeft().Text(item.EmployeeName).FontSize(8);
                                        table.Cell().Element(CellStyle).AlignRight().Text($"₱{item.NetSalary:N2}").FontSize(8).Bold().FontColor(global::QuestPDF.Helpers.Colors.Red.Darken2);
                                        table.Cell().Element(CellStyle).AlignLeft().Column(cellCol =>
                                        {
                                            cellCol.Item().Text(item.CancelledByName ?? "N/A").FontSize(8);
                                            if (!string.IsNullOrEmpty(item.CancelledByRole))
                                            {
                                                cellCol.Item().Text(item.CancelledByRole).FontSize(6).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                            }
                                        });
                                        table.Cell().Element(CellStyle).AlignLeft().Text(item.CreatedAt.ToString("MMM dd, yyyy")).FontSize(8);
                                        rowIndex++;
                                    }
                                });
                            }
                        }
                        else
                        {
                            // Standard Table for other report types
                            column.Item().PaddingTop(15).Text($"Payroll Transaction Records ({data.Count} records)").FontSize(12).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                            column.Item().PaddingTop(5).Table(table =>
                            {
                                table.ColumnsDefinition(columns =>
                                {
                                    if (reportType == "Detailed" || reportType == "ByEmployee")
                                    {
                                        columns.ConstantColumn(50); // Transaction ID
                                        columns.RelativeColumn(2);  // Employee
                                        columns.RelativeColumn(1.5f); // Pay Period
                                    }
                                    else if (reportType == "Summary" || reportType == "ByPayPeriod")
                                    {
                                        columns.RelativeColumn(2); // Period
                                    }
                                    else if (reportType == "ByStatus")
                                    {
                                        columns.RelativeColumn(1.5f); // Status
                                    }
                                    
                                    columns.RelativeColumn(1.5f); // Gross Pay
                                    columns.RelativeColumn(1.5f); // Deductions
                                    columns.RelativeColumn(1.5f); // Net Pay
                                    columns.RelativeColumn(1.5f); // Created By
                                    columns.RelativeColumn(1.5f); // Processed By
                                    columns.RelativeColumn(1.2f); // Status
                                    columns.RelativeColumn(1.5f); // Date
                                });

                            // Table Header - White background with colored text and separator line
                            table.Header(header =>
                            {
                                if (reportType == "Detailed" || reportType == "ByEmployee")
                                {
                                    header.Cell().Element(HeaderCellStyle).Text("Transaction ID").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignLeft();
                                    header.Cell().Element(HeaderCellStyle).Text("Employee").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignLeft();
                                    header.Cell().Element(HeaderCellStyle).Text("Pay Period").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignLeft();
                                }
                                else if (reportType == "Summary" || reportType == "ByPayPeriod")
                                {
                                    header.Cell().Element(HeaderCellStyle).Text("Period").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignLeft();
                                }
                                else if (reportType == "ByStatus")
                                {
                                    header.Cell().Element(HeaderCellStyle).Text("Status").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignLeft();
                                }
                                
                                header.Cell().Element(HeaderCellStyle).Text("Gross Pay").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignRight();
                                header.Cell().Element(HeaderCellStyle).Text("Deductions").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignRight();
                                header.Cell().Element(HeaderCellStyle).Text("Net Pay").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignRight();
                                header.Cell().Element(HeaderCellStyle).Text("Created By").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignLeft();
                                header.Cell().Element(HeaderCellStyle).Text("Processed By").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignLeft();
                                header.Cell().Element(HeaderCellStyle).Text("Status").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignLeft();
                                header.Cell().Element(HeaderCellStyle).Text("Date").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignLeft();
                            });

                            // Table Rows
                            int rowIndex = 1;
                            foreach (var item in data)
                            {
                                if (reportType == "Detailed" || reportType == "ByEmployee")
                                {
                                    table.Cell().Element(CellStyle).AlignLeft().Text($"Row {rowIndex}: #{item.TransactionId}").FontSize(8);
                                    table.Cell().Element(CellStyle).AlignLeft().Text(item.EmployeeName).FontSize(8);
                                    table.Cell().Element(CellStyle).AlignLeft().Text(item.PayPeriod).FontSize(8);
                                }
                                else if (reportType == "Summary" || reportType == "ByPayPeriod")
                                {
                                    table.Cell().Element(CellStyle).AlignLeft().Text($"Row {rowIndex}: {item.PayPeriod}").FontSize(8);
                                }
                                else if (reportType == "ByStatus")
                                {
                                    table.Cell().Element(CellStyle).AlignLeft().Text($"Row {rowIndex}: {item.Status}").FontSize(8);
                                }
                                
                                table.Cell().Element(CellStyle).AlignRight().Text($"₱{item.GrossSalary:N2}").FontSize(8);
                                table.Cell().Element(CellStyle).AlignRight().Text($"₱{item.TotalDeductions:N2}").FontSize(8);
                                table.Cell().Element(CellStyle).AlignRight().Text($"₱{item.NetSalary:N2}").FontSize(8).Bold();
                                
                                // Created By with Role
                                table.Cell().Element(CellStyle).AlignLeft().Column(cellCol =>
                                {
                                    cellCol.Item().Text(item.CreatedByName ?? "System").FontSize(8);
                                    if (!string.IsNullOrEmpty(item.CreatedByRole))
                                    {
                                        cellCol.Item().Text(item.CreatedByRole).FontSize(6).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                    }
                                });
                                
                                // Processed By with Role
                                var processedByName = item.Status == "Paid" 
                                    ? (item.ProcessedByName ?? item.ApprovedByName ?? "N/A")
                                    : (item.Status == "Cancelled" 
                                        ? (item.CancelledByName ?? "N/A")
                                        : "—");
                                var processedByRole = item.Status == "Paid"
                                    ? (item.ProcessedByRole ?? item.ApprovedByRole)
                                    : (item.Status == "Cancelled" ? item.CancelledByRole : null);
                                
                                table.Cell().Element(CellStyle).AlignLeft().Column(cellCol =>
                                {
                                    cellCol.Item().Text(processedByName).FontSize(8);
                                    if (!string.IsNullOrEmpty(processedByRole))
                                    {
                                        cellCol.Item().Text(processedByRole).FontSize(6).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                    }
                                });
                                
                                table.Cell().Element(CellStyle).AlignLeft().Text(item.Status).FontSize(8);
                                table.Cell().Element(CellStyle).AlignLeft().Text(item.CreatedAt.ToString("MMMM dd, yyyy")).FontSize(8);
                                rowIndex++;
                            }
                        });
                        }
                    });

                // Footer
                page.Footer()
                    .AlignCenter()
                    .DefaultTextStyle(x => x.FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Medium))
                    .Text(x =>
                    {
                        x.Span("Page ");
                        x.CurrentPageNumber();
                        x.Span(" of ");
                        x.TotalPages();
                        x.Span(" | Generated by BRIGHTENROLL ENROLLMENT MANAGEMENT SYSTEM");
                    });
            });
        }).GeneratePdf();
    }

    private static global::QuestPDF.Infrastructure.IContainer CellStyle(global::QuestPDF.Infrastructure.IContainer container)
    {
        return container
            .BorderBottom(1)
            .BorderColor(global::QuestPDF.Helpers.Colors.Grey.Lighten2)
            .PaddingVertical(5)
            .PaddingHorizontal(5)
            .Background(global::QuestPDF.Helpers.Colors.White);
    }

    private static global::QuestPDF.Infrastructure.IContainer HeaderCellStyle(global::QuestPDF.Infrastructure.IContainer container)
    {
        return container
            .Border(0)
            .BorderBottom(1)
            .BorderColor(global::QuestPDF.Helpers.Colors.Grey.Darken1)
            .PaddingVertical(5)
            .PaddingHorizontal(5)
            .ExtendHorizontal()
            .Background(global::QuestPDF.Helpers.Colors.White);
    }

    private string GetReportTitle(string reportType)
    {
        return reportType switch
        {
            "Summary" => "Payroll Summary Report",
            "Detailed" => "Detailed Payroll Report",
            "ByEmployee" => "Payroll Report by Employee",
            "ByStatus" => "Payroll Report by Status",
            "ByPayPeriod" => "Payroll Report by Pay Period",
            "CompanyContributions" => "Company Contributions Report",
            "AuditTrail" => "Audit Trail Report",
            _ => "Payroll Report"
        };
    }
}

// Data transfer object for PDF generation
public class PayrollReportDataItem
{
    public int TransactionId { get; set; }
    public string EmployeeName { get; set; } = string.Empty;
    public string PayPeriod { get; set; } = string.Empty;
    public decimal GrossSalary { get; set; }
    public decimal TotalDeductions { get; set; }
    public decimal NetSalary { get; set; }
    public string Status { get; set; } = string.Empty;
    public DateTime CreatedAt { get; set; }
    public decimal CompanySssContribution { get; set; }
    public decimal CompanyPhilHealthContribution { get; set; }
    public decimal CompanyPagIbigContribution { get; set; }
    public decimal TotalCompanyContribution { get; set; }
    public string CreatedByName { get; set; } = string.Empty;
    public string? CreatedByRole { get; set; }
    public string? ApprovedByName { get; set; }
    public string? ApprovedByRole { get; set; }
    public string? CancelledByName { get; set; }
    public string? CancelledByRole { get; set; }
    public string? ProcessedByName { get; set; }
    public string? ProcessedByRole { get; set; }
}

