using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.IO;

namespace BrightEnroll_DES.Services.QuestPDF;

public class PayrollReportPdfGenerator
{
    private byte[]? _logoBytes;

    private byte[] GetLogoBytes()
    {
        if (_logoBytes != null) return _logoBytes;
        
        var logoPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "lightlogo.png");
        if (File.Exists(logoPath))
        {
            _logoBytes = File.ReadAllBytes(logoPath);
        }
        return _logoBytes ?? Array.Empty<byte>();
    }

    public byte[] GeneratePayrollReport(
        List<PayrollReportDataItem> data,
        string reportType,
        string generatedBy,
        string userRole,
        DateTime? dateFrom = null,
        DateTime? dateTo = null,
        string? statusFilter = null,
        string? schoolYearFilter = null,
        string? employeeFilter = null)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(1.5f, Unit.Centimetre);
                page.PageColor(global::QuestPDF.Helpers.Colors.White);
                page.DefaultTextStyle(x => x.FontSize(10));

                // Header with Logo
                page.Header()
                    .PaddingBottom(10)
                    .Column(column =>
                    {
                        column.Item().Row(row =>
                        {
                            var logoBytes = GetLogoBytes();
                            if (logoBytes.Length > 0)
                            {
                                row.ConstantItem(60).Height(60).Image(logoBytes).FitArea();
                            }
                            else
                            {
                                row.ConstantItem(60).Height(60).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3)
                                    .AlignCenter().AlignMiddle()
                                    .Text("BE").FontSize(20).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                            }
                            
                            row.RelativeItem().PaddingLeft(15).Column(headerCol =>
                            {
                                headerCol.Item().Text("BRIGHTENROLL").FontSize(18).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                headerCol.Item().Text("ENROLLMENT MANAGEMENT SYSTEM").FontSize(10).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                headerCol.Item().PaddingTop(3).Text("Payroll Department").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                            });
                        });
                        
                        column.Item().PaddingTop(8).BorderBottom(2).BorderColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                    });

                // Content
                page.Content()
                    .PaddingVertical(10)
                    .Column(column =>
                    {
                        // Report Title
                        column.Item().Column(titleCol =>
                        {
                            titleCol.Item().Text(GetReportTitle(reportType)).FontSize(20).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                            titleCol.Item().PaddingTop(2).Text("Payroll Transaction Report").FontSize(12).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                        });

                        // Report Information Box
                        column.Item().PaddingTop(10).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Grey.Lighten2)
                            .Padding(12).Background(global::QuestPDF.Helpers.Colors.White)
                            .Column(infoCol =>
                            {
                                infoCol.Item().Row(row =>
                                {
                                    row.RelativeItem().Column(col =>
                                    {
                                        col.Item().Text("Generated By:").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                        col.Item().PaddingTop(1).Text($"{generatedBy} ({userRole})").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken2);
                                    });
                                    row.RelativeItem().Column(col =>
                                    {
                                        col.Item().Text("Generated On:").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                        col.Item().PaddingTop(1).Text(DateTime.Now.ToString("MMMM dd, yyyy 'at' hh:mm tt")).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                    });
                                });

                                infoCol.Item().PaddingTop(8).Row(row =>
                                {
                                    row.RelativeItem().Column(col =>
                                    {
                                        col.Item().Text("Date Range:").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                        var dateRange = dateFrom.HasValue && dateTo.HasValue
                                            ? $"{dateFrom.Value:MMMM dd, yyyy} to {dateTo.Value:MMMM dd, yyyy}"
                                            : "All Dates";
                                        col.Item().PaddingTop(1).Text(dateRange).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                    });
                                    row.RelativeItem().Column(col =>
                                    {
                                        col.Item().Text("Total Records:").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                        col.Item().PaddingTop(1).Text(data.Count.ToString()).FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken2);
                                    });
                                });

                                if (!string.IsNullOrEmpty(statusFilter))
                                {
                                    infoCol.Item().PaddingTop(5).Row(row =>
                                    {
                                        row.RelativeItem().Column(col =>
                                        {
                                            col.Item().Text("Status Filter:").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                            col.Item().PaddingTop(1).Text(statusFilter).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                        });
                                    });
                                }

                                if (!string.IsNullOrEmpty(schoolYearFilter))
                                {
                                    infoCol.Item().PaddingTop(5).Row(row =>
                                    {
                                        row.RelativeItem().Column(col =>
                                        {
                                            col.Item().Text("School Year:").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                            col.Item().PaddingTop(1).Text(schoolYearFilter).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                        });
                                    });
                                }
                            });

                        // Financial Summary - Simplified
                        var paidData = data.Where(d => d.Status == "Paid").ToList();
                        var cancelledData = data.Where(d => d.Status == "Cancelled").ToList();
                        var pendingData = data.Where(d => d.Status == "Pending").ToList();
                        var totalCount = data.Count;
                        var paidCount = paidData.Count;
                        var cancelledCount = cancelledData.Count;
                        var pendingCount = pendingData.Count;
                        var paidPercentage = totalCount > 0 ? (paidCount * 100.0 / totalCount) : 0;
                        var cancelledPercentage = totalCount > 0 ? (cancelledCount * 100.0 / totalCount) : 0;
                        var totalPaidNetPay = paidData.Sum(d => d.NetSalary);
                        var totalPaidGrossPay = paidData.Sum(d => d.GrossSalary);
                        var totalPaidDeductions = paidData.Sum(d => d.TotalDeductions);
                        
                        column.Item().PaddingTop(15).Row(row =>
                        {
                            row.RelativeItem().Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Green.Lighten2)
                                .Padding(8).Background(global::QuestPDF.Helpers.Colors.Green.Lighten4)
                                .Column(card =>
                                {
                                    card.Item().Text("Amount Paid").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                    card.Item().PaddingTop(1).Text($"₱{totalPaidNetPay:N2}").FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Green.Darken2);
                                    card.Item().PaddingTop(1).Text($"{paidCount} transaction(s)").FontSize(7).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                });
                            
                            row.RelativeItem().PaddingLeft(6).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Blue.Lighten2)
                                .Padding(8).Background(global::QuestPDF.Helpers.Colors.Blue.Lighten4)
                                .Column(card =>
                                {
                                    card.Item().Text("Gross Payroll").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                    card.Item().PaddingTop(1).Text($"₱{totalPaidGrossPay:N2}").FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken2);
                                    card.Item().PaddingTop(1).Text("Before deductions").FontSize(7).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                });
                            
                            row.RelativeItem().PaddingLeft(6).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Orange.Lighten2)
                                .Padding(8).Background(global::QuestPDF.Helpers.Colors.Orange.Lighten4)
                                .Column(card =>
                                {
                                    card.Item().Text("Total Deductions").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                    card.Item().PaddingTop(1).Text($"₱{totalPaidDeductions:N2}").FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Orange.Darken2);
                                    card.Item().PaddingTop(1).Text("SSS, PhilHealth, Tax").FontSize(7).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                });
                        });
                        
                        // Insights & Recommendations Section
                        column.Item().PaddingTop(12).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Blue.Lighten2)
                            .Padding(10).Background(global::QuestPDF.Helpers.Colors.Blue.Lighten4)
                            .Column(insightsCol =>
                            {
                                insightsCol.Item().Text("📊 Insights & Recommendations").FontSize(11).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                
                                insightsCol.Item().PaddingTop(4).Text($"• Status Distribution: {paidCount} paid ({paidPercentage:F1}%), {cancelledCount} cancelled ({cancelledPercentage:F1}%), {pendingCount} pending").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                
                                if (cancelledPercentage > 20)
                                {
                                    insightsCol.Item().PaddingTop(2).Text($"• ⚠️ High Cancellation Rate: {cancelledPercentage:F1}% exceeds normal threshold. Review cancellation reasons and improve validation processes.").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Orange.Darken2);
                                }
                                
                                if (paidPercentage > 80)
                                {
                                    insightsCol.Item().PaddingTop(2).Text($"• ✅ Excellent Processing: {paidPercentage:F1}% success rate indicates efficient payroll operations. Maintain current processes.").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Green.Darken2);
                                }
                                
                                if (cancelledCount > 0)
                                {
                                    insightsCol.Item().PaddingTop(2).Text($"• Action Required: Investigate {cancelledCount} cancelled transaction(s) to identify root causes and implement preventive measures.").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                }
                                
                                if (pendingCount > 0)
                                {
                                    insightsCol.Item().PaddingTop(2).Text($"• Pending Items: {pendingCount} transaction(s) awaiting processing. Review and process promptly to avoid delays.").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Yellow.Darken2);
                                }
                                
                                insightsCol.Item().PaddingTop(2).Text($"• Financial Impact: ₱{totalPaidNetPay:N2} successfully disbursed. ₱{cancelledData.Sum(d => d.NetSalary):N2} cancelled, requiring reconciliation.").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                
                                // Additional Recommendations
                                var recommendations = new List<string>();
                                if (cancelledCount > paidCount)
                                {
                                    recommendations.Add("Implement pre-validation checks before transaction creation to reduce cancellation rate");
                                }
                                if (pendingCount > 5)
                                {
                                    recommendations.Add("Establish automated processing workflows to reduce pending transaction backlog");
                                }
                                if (cancelledPercentage > 15)
                                {
                                    recommendations.Add("Conduct training sessions on proper payroll transaction procedures");
                                }
                                if (paidPercentage < 70 && totalCount > 10)
                                {
                                    recommendations.Add("Review and optimize payroll processing workflow to improve success rate");
                                }
                                
                                if (recommendations.Any())
                                {
                                    insightsCol.Item().PaddingTop(4).Text("Recommendations:").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                    foreach (var rec in recommendations)
                                    {
                                        insightsCol.Item().PaddingTop(1).Text($"  • {rec}").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                    }
                                }
                            });
                        

                        // Data Tables - Separated for Audit Trail
                        if (reportType == "AuditTrail")
                        {
                            
                            // Paid Transactions Table
                            if (paidData.Any())
                            {
                                column.Item().PaddingTop(15).Text($"✅ Paid Transactions ({paidData.Count})").FontSize(12).Bold().FontColor(global::QuestPDF.Helpers.Colors.Green.Darken2);
                                column.Item().PaddingTop(5).Table(table =>
                                {
                                    table.ColumnsDefinition(columns =>
                                    {
                                        columns.ConstantColumn(50); // Transaction ID
                                        columns.RelativeColumn(2.5f);  // Employee
                                        columns.RelativeColumn(1.5f); // Net Pay
                                        columns.RelativeColumn(2f); // Processed By
                                        columns.RelativeColumn(1.5f); // Date
                                    });
                                    
                                    // Header
                                    table.Header(header =>
                                    {
                                        header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Green.Darken2).Text("ID").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                        header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Green.Darken2).Text("Employee").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                        header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Green.Darken2).AlignRight().Text("Net Pay").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                        header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Green.Darken2).Text("Processed By").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                        header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Green.Darken2).Text("Date").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                    });
                                    
                                    // Rows
                                    foreach (var item in paidData)
                                    {
                                        table.Cell().Element(CellStyle).Text($"#{item.TransactionId}").FontSize(8);
                                        table.Cell().Element(CellStyle).Text(item.EmployeeName).FontSize(8);
                                        table.Cell().Element(CellStyle).AlignRight().Text($"₱{item.NetSalary:N2}").FontSize(8).Bold().FontColor(global::QuestPDF.Helpers.Colors.Green.Darken2);
                                        table.Cell().Element(CellStyle).Column(cellCol =>
                                        {
                                            cellCol.Item().Text(item.ProcessedByName ?? item.ApprovedByName ?? "N/A").FontSize(8);
                                            if (!string.IsNullOrEmpty(item.ProcessedByRole ?? item.ApprovedByRole))
                                            {
                                                cellCol.Item().Text(item.ProcessedByRole ?? item.ApprovedByRole).FontSize(6).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                            }
                                        });
                                        table.Cell().Element(CellStyle).Text(item.CreatedAt.ToString("MMM dd, yyyy")).FontSize(8);
                                    }
                                });
                            }
                            
                            // Cancelled Transactions Table
                            if (cancelledData.Any())
                            {
                                column.Item().PaddingTop(15).Text($"❌ Cancelled Transactions ({cancelledData.Count})").FontSize(12).Bold().FontColor(global::QuestPDF.Helpers.Colors.Red.Darken2);
                                column.Item().PaddingTop(5).Table(table =>
                                {
                                    table.ColumnsDefinition(columns =>
                                    {
                                        columns.ConstantColumn(50); // Transaction ID
                                        columns.RelativeColumn(2.5f);  // Employee
                                        columns.RelativeColumn(1.5f); // Net Pay
                                        columns.RelativeColumn(2f); // Cancelled By
                                        columns.RelativeColumn(1.5f); // Date
                                    });
                                    
                                    // Header
                                    table.Header(header =>
                                    {
                                        header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Red.Darken2).Text("ID").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                        header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Red.Darken2).Text("Employee").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                        header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Red.Darken2).AlignRight().Text("Net Pay").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                        header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Red.Darken2).Text("Cancelled By").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                        header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Red.Darken2).Text("Date").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                    });
                                    
                                    // Rows
                                    foreach (var item in cancelledData)
                                    {
                                        table.Cell().Element(CellStyle).Text($"#{item.TransactionId}").FontSize(8);
                                        table.Cell().Element(CellStyle).Text(item.EmployeeName).FontSize(8);
                                        table.Cell().Element(CellStyle).AlignRight().Text($"₱{item.NetSalary:N2}").FontSize(8).Bold().FontColor(global::QuestPDF.Helpers.Colors.Red.Darken2);
                                        table.Cell().Element(CellStyle).Column(cellCol =>
                                        {
                                            cellCol.Item().Text(item.CancelledByName ?? "N/A").FontSize(8);
                                            if (!string.IsNullOrEmpty(item.CancelledByRole))
                                            {
                                                cellCol.Item().Text(item.CancelledByRole).FontSize(6).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                            }
                                        });
                                        table.Cell().Element(CellStyle).Text(item.CreatedAt.ToString("MMM dd, yyyy")).FontSize(8);
                                    }
                                });
                            }
                        }
                        else
                        {
                            // Standard Table for other report types
                            column.Item().PaddingTop(15).Table(table =>
                            {
                                table.ColumnsDefinition(columns =>
                                {
                                    if (reportType == "Detailed" || reportType == "ByEmployee")
                                    {
                                        columns.ConstantColumn(50); // Transaction ID
                                        columns.RelativeColumn(2);  // Employee
                                        columns.RelativeColumn(1.5f); // Pay Period
                                    }
                                    else if (reportType == "Summary" || reportType == "ByPayPeriod")
                                    {
                                        columns.RelativeColumn(2); // Period
                                    }
                                    else if (reportType == "ByStatus")
                                    {
                                        columns.RelativeColumn(1.5f); // Status
                                    }
                                    
                                    columns.RelativeColumn(1.5f); // Gross Pay
                                    columns.RelativeColumn(1.5f); // Deductions
                                    columns.RelativeColumn(1.5f); // Net Pay
                                    
                                    if (reportType == "CompanyContributions")
                                    {
                                        columns.RelativeColumn(1.2f); // Company SSS
                                        columns.RelativeColumn(1.2f); // Company PhilHealth
                                        columns.RelativeColumn(1.2f); // Company Pag-IBIG
                                        columns.RelativeColumn(1.2f); // Total Company Contribution
                                    }
                                    
                                    columns.RelativeColumn(1.5f); // Created By
                                    columns.RelativeColumn(1.5f); // Processed By
                                    columns.RelativeColumn(1.2f); // Status
                                    columns.RelativeColumn(1.5f); // Date
                                });

                            // Table Header
                            table.Header(header =>
                            {
                                if (reportType == "Detailed" || reportType == "ByEmployee")
                                {
                                    header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3).Text("Transaction ID").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                    header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3).Text("Employee").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                    header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3).Text("Pay Period").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                }
                                else if (reportType == "Summary" || reportType == "ByPayPeriod")
                                {
                                    header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3).Text("Period").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                }
                                else if (reportType == "ByStatus")
                                {
                                    header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3).Text("Status").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                }
                                
                                header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignRight().Text("Gross Pay").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignRight().Text("Deductions").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignRight().Text("Net Pay").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                
                                if (reportType == "CompanyContributions")
                                {
                                    header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignRight().Text("Company SSS").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                    header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignRight().Text("Company PhilHealth").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                    header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignRight().Text("Company Pag-IBIG").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                    header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3).AlignRight().Text("Total Company Contribution").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                }
                                
                                header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3).Text("Created By").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3).Text("Processed By").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3).Text("Status").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                                header.Cell().Element(CellStyle).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3).Text("Date").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                            });

                            // Table Rows
                            foreach (var item in data)
                            {
                                if (reportType == "Detailed" || reportType == "ByEmployee")
                                {
                                    table.Cell().Element(CellStyle).Text($"#{item.TransactionId}").FontSize(8);
                                    table.Cell().Element(CellStyle).Text(item.EmployeeName).FontSize(8);
                                    table.Cell().Element(CellStyle).Text(item.PayPeriod).FontSize(8);
                                }
                                else if (reportType == "Summary" || reportType == "ByPayPeriod")
                                {
                                    table.Cell().Element(CellStyle).Text(item.PayPeriod).FontSize(8);
                                }
                                else if (reportType == "ByStatus")
                                {
                                    table.Cell().Element(CellStyle).Text(item.Status).FontSize(8);
                                }
                                
                                table.Cell().Element(CellStyle).AlignRight().Text($"₱{item.GrossSalary:N2}").FontSize(8);
                                table.Cell().Element(CellStyle).AlignRight().Text($"₱{item.TotalDeductions:N2}").FontSize(8);
                                table.Cell().Element(CellStyle).AlignRight().Text($"₱{item.NetSalary:N2}").FontSize(8).Bold();
                                
                                if (reportType == "CompanyContributions")
                                {
                                    table.Cell().Element(CellStyle).AlignRight().Text($"₱{item.CompanySssContribution:N2}").FontSize(8);
                                    table.Cell().Element(CellStyle).AlignRight().Text($"₱{item.CompanyPhilHealthContribution:N2}").FontSize(8);
                                    table.Cell().Element(CellStyle).AlignRight().Text($"₱{item.CompanyPagIbigContribution:N2}").FontSize(8);
                                    table.Cell().Element(CellStyle).AlignRight().Text($"₱{item.TotalCompanyContribution:N2}").FontSize(8).Bold();
                                }
                                
                                // Created By with Role
                                table.Cell().Element(CellStyle).Column(cellCol =>
                                {
                                    cellCol.Item().Text(item.CreatedByName ?? "System").FontSize(8);
                                    if (!string.IsNullOrEmpty(item.CreatedByRole))
                                    {
                                        cellCol.Item().Text(item.CreatedByRole).FontSize(6).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                    }
                                });
                                
                                // Processed By with Role
                                var processedByName = item.Status == "Paid" 
                                    ? (item.ProcessedByName ?? item.ApprovedByName ?? "N/A")
                                    : (item.Status == "Cancelled" 
                                        ? (item.CancelledByName ?? "N/A")
                                        : "—");
                                var processedByRole = item.Status == "Paid"
                                    ? (item.ProcessedByRole ?? item.ApprovedByRole)
                                    : (item.Status == "Cancelled" ? item.CancelledByRole : null);
                                
                                table.Cell().Element(CellStyle).Column(cellCol =>
                                {
                                    cellCol.Item().Text(processedByName).FontSize(8);
                                    if (!string.IsNullOrEmpty(processedByRole))
                                    {
                                        cellCol.Item().Text(processedByRole).FontSize(6).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                    }
                                });
                                
                                table.Cell().Element(CellStyle).Text(item.Status).FontSize(8);
                                table.Cell().Element(CellStyle).Text(item.CreatedAt.ToString("MMMM dd, yyyy")).FontSize(8);
                            }
                        });
                        }
                    });

                // Footer
                page.Footer()
                    .AlignCenter()
                    .DefaultTextStyle(x => x.FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Medium))
                    .Text(x =>
                    {
                        x.Span("Page ");
                        x.CurrentPageNumber();
                        x.Span(" of ");
                        x.TotalPages();
                        x.Span(" | Generated by BRIGHTENROLL ENROLLMENT MANAGEMENT SYSTEM");
                    });
            });
        }).GeneratePdf();
    }

    private static global::QuestPDF.Infrastructure.IContainer CellStyle(global::QuestPDF.Infrastructure.IContainer container)
    {
        return container
            .BorderBottom(1)
            .BorderColor(global::QuestPDF.Helpers.Colors.Grey.Lighten2)
            .PaddingVertical(5)
            .PaddingHorizontal(5)
            .Background(global::QuestPDF.Helpers.Colors.White);
    }

    private string GetReportTitle(string reportType)
    {
        return reportType switch
        {
            "Summary" => "Payroll Summary Report",
            "Detailed" => "Detailed Payroll Report",
            "ByEmployee" => "Payroll Report by Employee",
            "ByStatus" => "Payroll Report by Status",
            "ByPayPeriod" => "Payroll Report by Pay Period",
            "CompanyContributions" => "Company Contributions Report",
            "AuditTrail" => "Audit Trail Report",
            _ => "Payroll Report"
        };
    }
}

// Data transfer object for PDF generation
public class PayrollReportDataItem
{
    public int TransactionId { get; set; }
    public string EmployeeName { get; set; } = string.Empty;
    public string PayPeriod { get; set; } = string.Empty;
    public decimal GrossSalary { get; set; }
    public decimal TotalDeductions { get; set; }
    public decimal NetSalary { get; set; }
    public string Status { get; set; } = string.Empty;
    public DateTime CreatedAt { get; set; }
    public decimal CompanySssContribution { get; set; }
    public decimal CompanyPhilHealthContribution { get; set; }
    public decimal CompanyPagIbigContribution { get; set; }
    public decimal TotalCompanyContribution { get; set; }
    public string CreatedByName { get; set; } = string.Empty;
    public string? CreatedByRole { get; set; }
    public string? ApprovedByName { get; set; }
    public string? ApprovedByRole { get; set; }
    public string? CancelledByName { get; set; }
    public string? CancelledByRole { get; set; }
    public string? ProcessedByName { get; set; }
    public string? ProcessedByRole { get; set; }
}

