using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.IO;

namespace BrightEnroll_DES.Services.QuestPDF;

public class PayslipPdfGenerator
{
    private byte[]? _logoBytes;

    private byte[] GetLogoBytes()
    {
        if (_logoBytes != null) return _logoBytes;
        
        var logoPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "reportPDF.png");
        if (File.Exists(logoPath))
        {
            _logoBytes = File.ReadAllBytes(logoPath);
        }
        return _logoBytes ?? Array.Empty<byte>();
    }

    public byte[] GeneratePayslip(PayslipData payslipData, DateTime payPeriodStart, DateTime payPeriodEnd)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                // Standard A4 size for payslip
                page.Size(PageSizes.A4);
                page.Margin(1.5f, Unit.Centimetre);
                page.PageColor(global::QuestPDF.Helpers.Colors.White);
                page.DefaultTextStyle(x => x.FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black));

                // Enhanced Header - Two Column Layout
                page.Header()
                    .PaddingBottom(10)
                    .Column(headerColumn =>
                    {
                        // Top Row: Logo/Company Info on Left, Department/Date/Time on Right (matched heights)
                        headerColumn.Item().Height(50).Row(headerRow =>
                        {
                            // Left Side: Logo and Company Information
                            headerRow.RelativeItem(2).Row(leftRow =>
                            {
                                var logoBytes = GetLogoBytes();
                                if (logoBytes.Length > 0)
                                {
                                    leftRow.ConstantItem(50).Height(50).Image(logoBytes).FitArea();
                                }
                                
                                leftRow.RelativeItem().PaddingLeft(10).Column(companyCol =>
                                {
                                    companyCol.Item().Text("BRIGHTENROLL").FontSize(16).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                    companyCol.Item().PaddingTop(2).Text("ENROLLMENT MANAGEMENT SYSTEM").FontSize(10).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    companyCol.Item().PaddingTop(3).Text("Elementary School").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                });
                            });

                            // Right Side: Only Department, Date, and Time (matched height)
                            headerRow.RelativeItem(1).AlignRight().Column(detailsCol =>
                            {
                                detailsCol.Item().Text("PAYROLL DEPARTMENT").FontSize(10).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                                detailsCol.Item().PaddingTop(3).Row(row =>
                                {
                                    row.RelativeItem().Text("Date:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    row.RelativeItem().Text(DateTime.Now.ToString("MMMM dd, yyyy")).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                                detailsCol.Item().PaddingTop(2).Row(row =>
                                {
                                    row.RelativeItem().Text("Time:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    row.RelativeItem().Text(DateTime.Now.ToString("hh:mm tt")).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                            });
                        });
                        
                        // Border line below header row
                        headerColumn.Item().PaddingTop(8).BorderBottom(1).BorderColor(global::QuestPDF.Helpers.Colors.Black);
                        
                        // Report Details Below the Line: 2 Columns - Document Type/Payment Period on left, Generated By on right
                        headerColumn.Item().PaddingTop(8).Row(detailsRow =>
                        {
                            // Column 1: Document Type and Payment Period (stacked rows)
                            detailsRow.RelativeItem().Column(leftDetailsCol =>
                            {
                                leftDetailsCol.Item().Row(row =>
                                {
                                    row.ConstantItem(75).Text("Document Type:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    row.RelativeItem().Text("Payslip Receipt").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                                leftDetailsCol.Item().PaddingTop(2).Row(row =>
                                {
                                    row.ConstantItem(75).Text("Payment Period:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    row.RelativeItem().Text($"{payPeriodStart:MMMM yyyy}").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                            });
                            
                            // Column 2: Generated By
                            detailsRow.RelativeItem().AlignRight().Column(rightDetailsCol =>
                            {
                                rightDetailsCol.Item().Row(row =>
                                {
                                    row.ConstantItem(70).Text("Generated By:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    row.RelativeItem().Text("System").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black); // Payslips are system-generated
                                });
                            });
                        });
                    });

                // Content - Traditional Payslip Format
                page.Content()
                    .PaddingVertical(10)
                    .Column(column =>
                    {
                        // Employee Details Section
                        column.Item().Column(empCol =>
                        {
                            empCol.Item().Row(row =>
                            {
                                row.RelativeItem().Text("Name:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                row.RelativeItem().Text(payslipData.EmployeeName).FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                            });
                            empCol.Item().PaddingTop(3).Row(row =>
                            {
                                row.RelativeItem().Text("Employee No:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                row.RelativeItem().Text(payslipData.EmployeeId).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                            });
                            empCol.Item().PaddingTop(3).Row(row =>
                            {
                                row.RelativeItem().Text("Position:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                row.RelativeItem().Text(payslipData.Position).FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                            });
                        });

                        column.Item().PaddingTop(10).BorderTop(1).BorderColor(global::QuestPDF.Helpers.Colors.Black).PaddingTop(10);

                        // Two Column Layout: EARNINGS and DEDUCTIONS
                        column.Item().Row(row =>
                        {
                            // EARNINGS Column (Left)
                            row.RelativeItem(1).Column(earningsCol =>
                            {
                                earningsCol.Item().Text("EARNINGS").FontSize(10).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                                earningsCol.Item().PaddingTop(5).Row(itemRow =>
                                {
                                    itemRow.RelativeItem().Text("BASIC PAY:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    itemRow.RelativeItem().AlignRight().Text($"₱{payslipData.BaseSalary:N2}").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                                earningsCol.Item().PaddingTop(3).Row(itemRow =>
                                {
                                    itemRow.RelativeItem().Text("ALLOWANCE:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    itemRow.RelativeItem().AlignRight().Text($"₱{payslipData.Allowance:N2}").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                                earningsCol.Item().PaddingTop(8).BorderTop(0.5f).BorderColor(global::QuestPDF.Helpers.Colors.Black).PaddingTop(5);
                                earningsCol.Item().Row(itemRow =>
                                {
                                    itemRow.RelativeItem().Text("TOTAL EARNINGS:").FontSize(10).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    itemRow.RelativeItem().AlignRight().Text($"₱{payslipData.GrossPay:N2}").FontSize(10).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                            });

                            // DEDUCTIONS Column (Right)
                            row.RelativeItem(1).PaddingLeft(20).Column(deductionsCol =>
                            {
                                deductionsCol.Item().Text("DEDUCTIONS").FontSize(10).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                                deductionsCol.Item().PaddingTop(5).Row(itemRow =>
                                {
                                    itemRow.RelativeItem().Text("EMPLOYEE SSS:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    itemRow.RelativeItem().AlignRight().Text($"₱{payslipData.SSS:N2}").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                                deductionsCol.Item().PaddingTop(3).Row(itemRow =>
                                {
                                    itemRow.RelativeItem().Text("EMPLOYEE PHILHEALTH:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    itemRow.RelativeItem().AlignRight().Text($"₱{payslipData.PhilHealth:N2}").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                                deductionsCol.Item().PaddingTop(3).Row(itemRow =>
                                {
                                    itemRow.RelativeItem().Text("EMPLOYEE PAG-IBIG:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    itemRow.RelativeItem().AlignRight().Text($"₱{payslipData.PagIbig:N2}").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                                deductionsCol.Item().PaddingTop(3).Row(itemRow =>
                                {
                                    itemRow.RelativeItem().Text("EMPLOYEE TAX:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    itemRow.RelativeItem().AlignRight().Text($"₱{payslipData.WithholdingTax:N2}").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                                deductionsCol.Item().PaddingTop(8).BorderTop(0.5f).BorderColor(global::QuestPDF.Helpers.Colors.Black).PaddingTop(5);
                                deductionsCol.Item().Row(itemRow =>
                                {
                                    itemRow.RelativeItem().Text("TOTAL DEDUCTIONS:").FontSize(10).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                                    itemRow.RelativeItem().AlignRight().Text($"₱{payslipData.TotalDeductions:N2}").FontSize(10).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                                });
                            });
                        });

                        column.Item().PaddingTop(10).BorderTop(1).BorderColor(global::QuestPDF.Helpers.Colors.Black).PaddingTop(10);

                        // Net Salary Section
                        column.Item().Row(row =>
                        {
                            row.RelativeItem().Text("NET SALARY:").FontSize(12).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                            row.RelativeItem().AlignRight().Text($"₱{payslipData.NetPay:N2}").FontSize(12).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                        });

                        column.Item().PaddingTop(10).BorderTop(1).BorderColor(global::QuestPDF.Helpers.Colors.Black).PaddingTop(10);

                        // Employer Contributions Section
                        column.Item().Text("EMPLOYER CONTRIBUTIONS:").FontSize(10).Bold().FontColor(global::QuestPDF.Helpers.Colors.Black);
                        column.Item().PaddingTop(5).Row(row =>
                        {
                            row.RelativeItem().Text("EMPLOYER SSS:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                            row.RelativeItem().AlignRight().Text($"₱{(payslipData.BaseSalary * 0.085m):N2}").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                        });
                        column.Item().PaddingTop(3).Row(row =>
                        {
                            row.RelativeItem().Text("EMPLOYER PHILHEALTH:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                            row.RelativeItem().AlignRight().Text($"₱{(payslipData.BaseSalary * 0.015m):N2}").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                        });
                        column.Item().PaddingTop(3).Row(row =>
                        {
                            row.RelativeItem().Text("EMPLOYER PAG-IBIG:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                            row.RelativeItem().AlignRight().Text($"₱{payslipData.PagIbig:N2}").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                        });

                        column.Item().PaddingTop(15).BorderTop(1).BorderColor(global::QuestPDF.Helpers.Colors.Black).PaddingTop(15);

                        // Signature Section
                        column.Item().Row(row =>
                        {
                            row.RelativeItem(1).Column(sigCol =>
                            {
                                sigCol.Item().Text("CHECKED BY:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                sigCol.Item().PaddingTop(20).BorderBottom(0.5f).BorderColor(global::QuestPDF.Helpers.Colors.Black);
                            });
                            row.RelativeItem(1).PaddingLeft(20).Column(sigCol =>
                            {
                                sigCol.Item().Text("APPROVED BY:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                sigCol.Item().PaddingTop(20).BorderBottom(0.5f).BorderColor(global::QuestPDF.Helpers.Colors.Black);
                            });
                            row.RelativeItem(1).PaddingLeft(20).Column(sigCol =>
                            {
                                sigCol.Item().Text("RECEIVED BY:").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Black);
                                sigCol.Item().PaddingTop(20).BorderBottom(0.5f).BorderColor(global::QuestPDF.Helpers.Colors.Black);
                            });
                        });
                    });
            });
        }).GeneratePdf();
    }

    public class PayslipData
    {
        public string EmployeeId { get; set; } = string.Empty;
        public string EmployeeName { get; set; } = string.Empty;
        public string Position { get; set; } = string.Empty;
        public decimal BaseSalary { get; set; }
        public decimal Allowance { get; set; }
        public decimal GrossPay { get; set; }
        public decimal SSS { get; set; }
        public decimal PhilHealth { get; set; }
        public decimal PagIbig { get; set; }
        public decimal WithholdingTax { get; set; }
        public decimal TotalDeductions { get; set; }
        public decimal NetPay { get; set; }
        public string PayslipNumber { get; set; } = string.Empty;
        public string Status { get; set; } = string.Empty;
    }
}

