using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using BrightEnroll_DES.Services.Business.HR;
using System.IO;

namespace BrightEnroll_DES.Services.QuestPDF;

public class SalaryChangeLogPdfGenerator
{
    private byte[]? _logoBytes;

    private byte[] GetLogoBytes()
    {
        if (_logoBytes != null) return _logoBytes;
        
        var logoPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "lightlogo.png");
        if (File.Exists(logoPath))
        {
            _logoBytes = File.ReadAllBytes(logoPath);
        }
        return _logoBytes ?? Array.Empty<byte>();
    }

    public byte[] GenerateComprehensiveAuditReport(
        List<SalaryChangeLogDto> data,
        string generatedBy,
        string userRole,
        string? statusFilter = null,
        string? schoolYearFilter = null,
        DateTime? dateFrom = null,
        DateTime? dateTo = null)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(1.5f, Unit.Centimetre);
                page.PageColor(global::QuestPDF.Helpers.Colors.White);
                page.DefaultTextStyle(x => x.FontSize(10));

                // Enhanced Header with Logo
                page.Header()
                    .PaddingBottom(10)
                    .Column(column =>
                    {
                        column.Item().Row(row =>
                        {
                            var logoBytes = GetLogoBytes();
                            if (logoBytes.Length > 0)
                            {
                                row.ConstantItem(60).Height(60).Image(logoBytes).FitArea();
                            }
                            else
                            {
                                row.ConstantItem(60).Height(60).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3)
                                    .AlignCenter().AlignMiddle()
                                    .Text("BE").FontSize(20).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                            }
                            
                            row.RelativeItem().PaddingLeft(15).Column(headerCol =>
                            {
                                headerCol.Item().Text("BRIGHTENROLL").FontSize(18).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                headerCol.Item().Text("Enrollment Management System").FontSize(10).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                headerCol.Item().PaddingTop(3).Text("Human Resource Department").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                            });
                        });
                        
                        column.Item().PaddingTop(8).BorderBottom(2).BorderColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                    });

                // Content
                page.Content()
                    .Column(column =>
                    {
                        // Report Title
                        column.Item().PaddingTop(5).Column(titleCol =>
                        {
                            titleCol.Item().Text("SALARY CHANGE LOG").FontSize(20).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                            titleCol.Item().PaddingTop(2).Text("Comprehensive Audit Report").FontSize(12).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                        });

                        // Report Metadata - Clean Design
                        column.Item().PaddingTop(10).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Grey.Lighten2)
                            .Padding(12).Background(global::QuestPDF.Helpers.Colors.White)
                            .Column(metaCol =>
                            {
                                metaCol.Item().Row(row =>
                                {
                                    row.RelativeItem().Column(leftCol =>
                                    {
                                        leftCol.Item().Text($"Generated On: {DateTime.Now:MMMM dd, yyyy 'at' hh:mm tt}").FontSize(9);
                                        leftCol.Item().PaddingTop(3).Text($"Generated By: {generatedBy}").FontSize(9);
                                        leftCol.Item().PaddingTop(3).Text($"User Role: {userRole}").FontSize(9);
                                    });
                                    row.RelativeItem().Column(rightCol =>
                                    {
                                        rightCol.Item().Text($"Report Period: {(dateFrom.HasValue ? dateFrom.Value.ToString("MMMM dd, yyyy") : "All Time")} - {(dateTo.HasValue ? dateTo.Value.ToString("MMMM dd, yyyy") : "Present")}").FontSize(9);
                                        rightCol.Item().PaddingTop(3).Text($"Filters Applied:").FontSize(9).Bold();
                                        rightCol.Item().Text($"  • Status: {statusFilter ?? "All"}").FontSize(8);
                                        rightCol.Item().Text($"  • School Year: {schoolYearFilter ?? "All"}").FontSize(8);
                                    });
                                });
                            });

                        // Calculate Financial Metrics
                        var totalRecords = data.Count;
                        var approved = data.Count(d => d.Status == "Approved");
                        var rejected = data.Count(d => d.Status == "Rejected");
                        var pending = data.Count(d => d.Status == "Pending");
                        var approvedData = data.Where(d => d.Status == "Approved").ToList();
                        var totalIncrease = approvedData.Where(d => d.ChangeAmount > 0).Sum(d => d.ChangeAmount);
                        var totalDecrease = approvedData.Where(d => d.ChangeAmount < 0).Sum(d => Math.Abs(d.ChangeAmount));
                        var netChange = totalIncrease - totalDecrease;
                        var avgIncrease = approvedData.Where(d => d.ChangePercentage > 0).Any() 
                            ? approvedData.Where(d => d.ChangePercentage > 0).Average(d => (double)d.ChangePercentage) 
                            : 0;
                        var employeesAffected = data.Select(d => d.UserId).Distinct().Count();
                        
                        // Financial Impact Calculations
                        var monthlyImpact = netChange;
                        var annualImpact = monthlyImpact * 12;
                        var avgBaseSalary = approvedData.Any() ? approvedData.Average(d => (double)d.NewBaseSalary) : 0;
                        var avgAllowance = approvedData.Any() ? approvedData.Average(d => (double)d.NewAllowance) : 0;
                        var totalNewSalary = approvedData.Sum(d => d.NewTotalSalary);
                        var totalPreviousSalary = approvedData.Sum(d => d.PreviousTotalSalary);

                        // Executive Summary - Enhanced Cards
                        column.Item().PaddingTop(15).Column(summaryCol =>
                        {
                            summaryCol.Item().Text("Executive Summary").FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken2);
                            summaryCol.Item().PaddingTop(8).Row(row =>
                            {
                                row.RelativeItem().Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Blue.Lighten2)
                                    .Padding(10).Background(global::QuestPDF.Helpers.Colors.White)
                                    .Column(card =>
                                    {
                                        card.Item().Text("Total Records").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                        card.Item().PaddingTop(2).Text(totalRecords.ToString()).FontSize(18).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                    });
                                row.RelativeItem().PaddingLeft(8).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Green.Lighten2)
                                    .Padding(10).Background(global::QuestPDF.Helpers.Colors.White)
                                    .Column(card =>
                                    {
                                        card.Item().Text("Approved").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                        card.Item().PaddingTop(2).Text(approved.ToString()).FontSize(18).Bold().FontColor(global::QuestPDF.Helpers.Colors.Green.Darken2);
                                    });
                                row.RelativeItem().PaddingLeft(8).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Red.Lighten2)
                                    .Padding(10).Background(global::QuestPDF.Helpers.Colors.White)
                                    .Column(card =>
                                    {
                                        card.Item().Text("Rejected").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                        card.Item().PaddingTop(2).Text(rejected.ToString()).FontSize(18).Bold().FontColor(global::QuestPDF.Helpers.Colors.Red.Darken2);
                                    });
                                row.RelativeItem().PaddingLeft(8).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Yellow.Lighten2)
                                    .Padding(10).Background(global::QuestPDF.Helpers.Colors.White)
                                    .Column(card =>
                                    {
                                        card.Item().Text("Pending").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                        card.Item().PaddingTop(2).Text(pending.ToString()).FontSize(18).Bold().FontColor(global::QuestPDF.Helpers.Colors.Yellow.Darken2);
                                    });
                            });
                            
                            // Financial Impact Row
                            summaryCol.Item().PaddingTop(8).Row(row =>
                            {
                                row.RelativeItem().Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Green.Lighten2)
                                    .Padding(10).Background(global::QuestPDF.Helpers.Colors.White)
                                    .Column(card =>
                                    {
                                        card.Item().Text("Total Salary Increase").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                        card.Item().PaddingTop(2).Text($"₱{totalIncrease:N2}").FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Green.Darken2);
                                    });
                                row.RelativeItem().PaddingLeft(8).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Blue.Lighten2)
                                    .Padding(10).Background(global::QuestPDF.Helpers.Colors.White)
                                    .Column(card =>
                                    {
                                        card.Item().Text("Net Salary Change").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                        card.Item().PaddingTop(2).Text($"₱{netChange:N2}").FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                    });
                                row.RelativeItem().PaddingLeft(8).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Blue.Lighten2)
                                    .Padding(10).Background(global::QuestPDF.Helpers.Colors.White)
                                    .Column(card =>
                                    {
                                        card.Item().Text("Average Increase %").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                        card.Item().PaddingTop(2).Text($"{avgIncrease:F2}%").FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                    });
                                row.RelativeItem().PaddingLeft(8).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Blue.Lighten2)
                                    .Padding(10).Background(global::QuestPDF.Helpers.Colors.White)
                                    .Column(card =>
                                    {
                                        card.Item().Text("Employees Affected").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                        card.Item().PaddingTop(2).Text(employeesAffected.ToString()).FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                    });
                            });
                        });

                        // Financial Impact Report Section
                        column.Item().PaddingTop(20).Column(financialCol =>
                        {
                            financialCol.Item().Text("Financial Impact Analysis").FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken2);
                            financialCol.Item().PaddingTop(8).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Grey.Lighten2)
                                .Padding(12).Background(global::QuestPDF.Helpers.Colors.White)
                                .Table(table =>
                                {
                                    table.ColumnsDefinition(columns =>
                                    {
                                        columns.RelativeColumn(2);
                                        columns.RelativeColumn(2);
                                    });

                                    table.Cell().Element(c => CellStyle(c)).Text("Metric").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                    table.Cell().Element(c => CellStyle(c)).Text("Value").FontSize(9).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                    
                                    table.Cell().Element(c => CellStyle(c)).Text("Total Previous Salary (Approved)").FontSize(8);
                                    table.Cell().Element(c => CellStyle(c)).Text($"₱{totalPreviousSalary:N2}").FontSize(8).Bold();
                                    
                                    table.Cell().Element(c => CellStyle(c)).Text("Total New Salary (Approved)").FontSize(8);
                                    table.Cell().Element(c => CellStyle(c)).Text($"₱{totalNewSalary:N2}").FontSize(8).Bold();
                                    
                                    table.Cell().Element(c => CellStyle(c)).Text("Monthly Salary Impact").FontSize(8);
                                    table.Cell().Element(c => CellStyle(c)).Text($"₱{monthlyImpact:N2}").FontSize(8).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                    
                                    table.Cell().Element(c => CellStyle(c)).Text("Annual Salary Impact").FontSize(8);
                                    table.Cell().Element(c => CellStyle(c)).Text($"₱{annualImpact:N2}").FontSize(8).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                    
                                    table.Cell().Element(c => CellStyle(c)).Text("Average Monthly Salary (New)").FontSize(8);
                                    table.Cell().Element(c => CellStyle(c)).Text($"₱{avgBaseSalary:N2}").FontSize(8);
                                    
                                    table.Cell().Element(c => CellStyle(c)).Text("Average Allowance (New)").FontSize(8);
                                    table.Cell().Element(c => CellStyle(c)).Text($"₱{avgAllowance:N2}").FontSize(8);
                                    
                                    table.Cell().Element(c => CellStyle(c)).Text("Total Salary Increase").FontSize(8);
                                    table.Cell().Element(c => CellStyle(c)).Text($"₱{totalIncrease:N2}").FontSize(8).Bold().FontColor(global::QuestPDF.Helpers.Colors.Green.Darken2);
                                    
                                    table.Cell().Element(c => CellStyle(c)).Text("Total Salary Decrease").FontSize(8);
                                    table.Cell().Element(c => CellStyle(c)).Text($"₱{totalDecrease:N2}").FontSize(8).Bold().FontColor(global::QuestPDF.Helpers.Colors.Red.Darken2);
                                });
                        });

                        // Detailed Table - Enhanced
                        column.Item().PaddingTop(20).Column(tableCol =>
                        {
                            tableCol.Item().Text("Detailed Records").FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken2);
                            tableCol.Item().PaddingTop(5).Table(table =>
                            {
                                table.ColumnsDefinition(columns =>
                                {
                                    columns.RelativeColumn(2);
                                    columns.RelativeColumn(1.5f);
                                    columns.RelativeColumn(1.5f);
                                    columns.RelativeColumn(1.5f);
                                    columns.RelativeColumn(1.5f);
                                    columns.RelativeColumn(1.2f);
                                    columns.RelativeColumn(1.2f);
                                    columns.RelativeColumn(1.2f);
                                });

                                // Header
                                table.Header(header =>
                                {
                                    header.Cell().Element(c => HeaderCellStyle(c)).Text("Employee").FontSize(9).Bold();
                                    header.Cell().Element(c => HeaderCellStyle(c)).Text("Role").FontSize(9).Bold();
                                    header.Cell().Element(c => HeaderCellStyle(c)).Text("Previous").FontSize(9).Bold();
                                    header.Cell().Element(c => HeaderCellStyle(c)).Text("New Salary").FontSize(9).Bold();
                                    header.Cell().Element(c => HeaderCellStyle(c)).Text("Change %").FontSize(9).Bold();
                                    header.Cell().Element(c => HeaderCellStyle(c)).Text("Status").FontSize(9).Bold();
                                    header.Cell().Element(c => HeaderCellStyle(c)).Text("Requested").FontSize(9).Bold();
                                    header.Cell().Element(c => HeaderCellStyle(c)).Text("Approved").FontSize(9).Bold();
                                });

                                // Rows
                                var rowIndex = 0;
                                foreach (var entry in data)
                                {
                                    var bgColor = rowIndex % 2 == 0 ? global::QuestPDF.Helpers.Colors.White : global::QuestPDF.Helpers.Colors.Grey.Lighten4;
                                    table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text($"{entry.EmployeeName}\n{entry.EmployeeId}").FontSize(8);
                                    table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text(entry.Role).FontSize(8);
                                    table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text($"₱{entry.PreviousTotalSalary:N2}").FontSize(8);
                                    table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text($"₱{entry.NewTotalSalary:N2}").FontSize(8);
                                    table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text($"{entry.ChangePercentage:F2}%").FontSize(8);
                                    table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text(entry.Status).FontSize(8);
                                    table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text($"{entry.RequestedByName}\n{entry.RequestedAt:MMM dd, yyyy}").FontSize(8);
                                    table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text(entry.ApproverName ?? "—").FontSize(8);
                                    rowIndex++;
                                }
                            });
                        });
                    });

                // Footer
                page.Footer()
                    .PaddingTop(10)
                    .BorderTop(1).BorderColor(global::QuestPDF.Helpers.Colors.Grey.Lighten2)
                    .Row(row =>
                    {
                        row.RelativeItem().Text("Confidential — For Internal Use Only").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Medium);
                        row.RelativeItem().AlignCenter().Text("Report Generated by HRIS System").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Medium);
                        row.RelativeItem().AlignRight()
                            .DefaultTextStyle(x => x.FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Medium))
                            .Text(x =>
                            {
                                x.Span("Page ");
                                x.CurrentPageNumber();
                                x.Span(" of ");
                                x.TotalPages();
                            });
                    });
            });
        }).GeneratePdf();
    }

    public byte[] GenerateStatisticalReport(
        List<SalaryChangeLogDto> data,
        string generatedBy,
        string userRole,
        string? statusFilter = null,
        string? schoolYearFilter = null)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(1.5f, Unit.Centimetre);
                page.PageColor(global::QuestPDF.Helpers.Colors.White);
                page.DefaultTextStyle(x => x.FontSize(10));

                // Enhanced Header with Logo
                page.Header()
                    .PaddingBottom(10)
                    .Column(column =>
                    {
                        column.Item().Row(row =>
                        {
                            var logoBytes = GetLogoBytes();
                            if (logoBytes.Length > 0)
                            {
                                row.ConstantItem(60).Height(60).Image(logoBytes).FitArea();
                            }
                            else
                            {
                                row.ConstantItem(60).Height(60).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3)
                                    .AlignCenter().AlignMiddle()
                                    .Text("BE").FontSize(20).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                            }
                            
                            row.RelativeItem().PaddingLeft(15).Column(headerCol =>
                            {
                                headerCol.Item().Text("BRIGHTENROLL").FontSize(18).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                headerCol.Item().Text("Enrollment Management System").FontSize(10).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                headerCol.Item().PaddingTop(3).Text("Human Resource Department").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                            });
                        });
                        
                        column.Item().PaddingTop(8).BorderBottom(2).BorderColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                    });

                page.Content()
                    .Column(column =>
                    {
                        // Report Title
                        column.Item().PaddingTop(5).Column(titleCol =>
                        {
                            titleCol.Item().Text("SALARY CHANGE LOG").FontSize(20).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                            titleCol.Item().PaddingTop(2).Text("Statistical Analysis Report with Recommendations").FontSize(12).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                        });

                        // Metadata - Clean Design
                        column.Item().PaddingTop(10).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Grey.Lighten2)
                            .Padding(12).Background(global::QuestPDF.Helpers.Colors.White)
                            .Column(metaCol =>
                            {
                                metaCol.Item().Text($"Generated On: {DateTime.Now:MMMM dd, yyyy 'at' hh:mm tt}").FontSize(9);
                                metaCol.Item().PaddingTop(3).Text($"Generated By: {generatedBy} ({userRole})").FontSize(9);
                                metaCol.Item().PaddingTop(3).Text($"Filters: Status={statusFilter ?? "All"}, School Year={schoolYearFilter ?? "All"}").FontSize(9);
                            });

                        // Statistics
                        var stats = CalculateStatistics(data);
                        
                        column.Item().PaddingTop(15).Column(statsCol =>
                        {
                            statsCol.Item().Text("Statistical Analysis").FontSize(16).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken2);
                            
                            // Summary Statistics - Enhanced Cards
                            statsCol.Item().PaddingTop(10).Row(row =>
                            {
                                row.RelativeItem().Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Blue.Lighten2)
                                    .Padding(10).Background(global::QuestPDF.Helpers.Colors.White)
                                    .Column(card =>
                                    {
                                        card.Item().Text("Total Changes").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                        card.Item().PaddingTop(2).Text(stats.TotalChanges.ToString()).FontSize(18).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                    });
                                row.RelativeItem().PaddingLeft(8).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Green.Lighten2)
                                    .Padding(10).Background(global::QuestPDF.Helpers.Colors.White)
                                    .Column(card =>
                                    {
                                        card.Item().Text("Approval Rate").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                        card.Item().PaddingTop(2).Text($"{stats.ApprovalRate:F1}%").FontSize(18).Bold().FontColor(global::QuestPDF.Helpers.Colors.Green.Darken2);
                                    });
                                row.RelativeItem().PaddingLeft(8).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Blue.Lighten2)
                                    .Padding(10).Background(global::QuestPDF.Helpers.Colors.White)
                                    .Column(card =>
                                    {
                                        card.Item().Text("Avg Increase %").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                                        card.Item().PaddingTop(2).Text($"{stats.AverageIncreasePercent:F2}%").FontSize(18).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                    });
                            });

                            // Department Breakdown
                            statsCol.Item().PaddingTop(15).Text("Department Breakdown").FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken2);
                            statsCol.Item().PaddingTop(5).Table(table =>
                            {
                                table.ColumnsDefinition(columns =>
                                {
                                    columns.RelativeColumn(2);
                                    columns.RelativeColumn(1.5f);
                                    columns.RelativeColumn(2);
                                    columns.RelativeColumn(1.5f);
                                    columns.RelativeColumn(1.5f);
                                });

                                table.Header(header =>
                                {
                                    header.Cell().Element(c => HeaderCellStyle(c)).Text("Department").FontSize(9).Bold();
                                    header.Cell().Element(c => HeaderCellStyle(c)).Text("# Employees").FontSize(9).Bold();
                                    header.Cell().Element(c => HeaderCellStyle(c)).Text("Total Increase").FontSize(9).Bold();
                                    header.Cell().Element(c => HeaderCellStyle(c)).Text("Avg %").FontSize(9).Bold();
                                    header.Cell().Element(c => HeaderCellStyle(c)).Text("Highest %").FontSize(9).Bold();
                                });

                                var deptIndex = 0;
                                foreach (var dept in stats.DepartmentBreakdown)
                                {
                                    var bgColor = deptIndex % 2 == 0 ? global::QuestPDF.Helpers.Colors.White : global::QuestPDF.Helpers.Colors.Grey.Lighten4;
                                    table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text(dept.Department).FontSize(8);
                                    table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text(dept.EmployeeCount.ToString()).FontSize(8);
                                    table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text($"₱{dept.TotalIncrease:N2}").FontSize(8);
                                    table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text($"{dept.AverageIncreasePercent:F2}%").FontSize(8);
                                    table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text($"{dept.HighestIncreasePercent:F2}%").FontSize(8);
                                    deptIndex++;
                                }
                            });

                            // School Year Breakdown
                            statsCol.Item().PaddingTop(15).Text("School Year Breakdown").FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken2);
                            statsCol.Item().PaddingTop(5).Table(table =>
                            {
                                table.ColumnsDefinition(columns =>
                                {
                                    columns.RelativeColumn(2);
                                    columns.RelativeColumn(1.5f);
                                    columns.RelativeColumn(2);
                                    columns.RelativeColumn(2);
                                    columns.RelativeColumn(1.5f);
                                });

                                table.Header(header =>
                                {
                                    header.Cell().Element(c => HeaderCellStyle(c)).Text("School Year").FontSize(9).Bold();
                                    header.Cell().Element(c => HeaderCellStyle(c)).Text("# Changes").FontSize(9).Bold();
                                    header.Cell().Element(c => HeaderCellStyle(c)).Text("Total Increase").FontSize(9).Bold();
                                    header.Cell().Element(c => HeaderCellStyle(c)).Text("Net Change").FontSize(9).Bold();
                                    header.Cell().Element(c => HeaderCellStyle(c)).Text("Avg %").FontSize(9).Bold();
                                });

                                var yearIndex = 0;
                                foreach (var year in stats.SchoolYearBreakdown)
                                {
                                    var bgColor = yearIndex % 2 == 0 ? global::QuestPDF.Helpers.Colors.White : global::QuestPDF.Helpers.Colors.Grey.Lighten4;
                                    table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text(year.SchoolYear).FontSize(8);
                                    table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text(year.ChangeCount.ToString()).FontSize(8);
                                    table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text($"₱{year.TotalIncrease:N2}").FontSize(8);
                                    table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text($"₱{year.NetChange:N2}").FontSize(8);
                                    table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text($"{year.AverageIncreasePercent:F2}%").FontSize(8);
                                    yearIndex++;
                                }
                            });

                            // Recommendations - Enhanced Design
                            statsCol.Item().PaddingTop(15).Text("Recommendations & Insights").FontSize(16).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken2);
                            statsCol.Item().PaddingTop(5).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Blue.Lighten2)
                                .Padding(12).Background(global::QuestPDF.Helpers.Colors.White)
                                .Column(recCol =>
                                {
                                    foreach (var recommendation in stats.Recommendations)
                                    {
                                        recCol.Item().PaddingBottom(5).Row(row =>
                                        {
                                            row.ConstantItem(15).Text("•").FontSize(10).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                            row.RelativeItem().Text(recommendation).FontSize(9);
                                        });
                                    }
                                });
                        });
                    });

                page.Footer()
                    .PaddingTop(10)
                    .BorderTop(1).BorderColor(global::QuestPDF.Helpers.Colors.Grey.Lighten2)
                    .Row(row =>
                    {
                        row.RelativeItem().Text("Confidential — For Internal Use Only").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Medium);
                        row.RelativeItem().AlignCenter().Text("Report Generated by HRIS System").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Medium);
                        row.RelativeItem().AlignRight()
                            .DefaultTextStyle(x => x.FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Medium))
                            .Text(x =>
                            {
                                x.Span("Page ");
                                x.CurrentPageNumber();
                                x.Span(" of ");
                                x.TotalPages();
                            });
                    });
            });
        }).GeneratePdf();
    }

    public byte[] GenerateEmployeeHistoryReport(SalaryChangeLogDto employee, List<SalaryChangeLogDto> history, string generatedBy, string userRole)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(1.5f, Unit.Centimetre);
                page.PageColor(global::QuestPDF.Helpers.Colors.White);
                page.DefaultTextStyle(x => x.FontSize(10));

                // Enhanced Header with Logo
                page.Header()
                    .PaddingBottom(10)
                    .Column(column =>
                    {
                        column.Item().Row(row =>
                        {
                            var logoBytes = GetLogoBytes();
                            if (logoBytes.Length > 0)
                            {
                                row.ConstantItem(60).Height(60).Image(logoBytes).FitArea();
                            }
                            else
                            {
                                row.ConstantItem(60).Height(60).Background(global::QuestPDF.Helpers.Colors.Blue.Darken3)
                                    .AlignCenter().AlignMiddle()
                                    .Text("BE").FontSize(20).Bold().FontColor(global::QuestPDF.Helpers.Colors.White);
                            }
                            
                            row.RelativeItem().PaddingLeft(15).Column(headerCol =>
                            {
                                headerCol.Item().Text("BRIGHTENROLL").FontSize(18).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                headerCol.Item().Text("Enrollment Management System").FontSize(10).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken2);
                                headerCol.Item().PaddingTop(3).Text("Employee Salary History Report").FontSize(9).FontColor(global::QuestPDF.Helpers.Colors.Grey.Darken1);
                            });
                        });
                        
                        column.Item().PaddingTop(8).BorderBottom(2).BorderColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                    });

                page.Content()
                    .Column(column =>
                    {
                        // Employee Information - Enhanced Design
                        column.Item().PaddingTop(5).Border(1).BorderColor(global::QuestPDF.Helpers.Colors.Blue.Lighten2)
                            .Padding(15).Background(global::QuestPDF.Helpers.Colors.White)
                            .Column(empCol =>
                            {
                                empCol.Item().Text("Employee Information").FontSize(14).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken3);
                                empCol.Item().PaddingTop(5).Row(row =>
                                {
                                    row.RelativeItem().Text($"Name: {employee.EmployeeName}").FontSize(10);
                                    row.RelativeItem().Text($"ID: {employee.EmployeeId}").FontSize(10);
                                });
                                empCol.Item().PaddingTop(3).Row(row =>
                                {
                                    row.RelativeItem().Text($"Position: {employee.Role}").FontSize(10);
                                });
                            });

                        // Salary History Timeline
                        column.Item().PaddingTop(15).Text("Salary History Timeline").FontSize(16).Bold().FontColor(global::QuestPDF.Helpers.Colors.Blue.Darken2);
                        column.Item().PaddingTop(5).Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(1.5f);
                                columns.RelativeColumn(1.5f);
                                columns.RelativeColumn(1.5f);
                                columns.RelativeColumn(1.5f);
                                columns.RelativeColumn(1.2f);
                                columns.RelativeColumn(1.5f);
                                columns.RelativeColumn(1.3f);
                            });

                            table.Header(header =>
                            {
                                header.Cell().Element(c => HeaderCellStyle(c)).Text("Date").FontSize(9).Bold();
                                header.Cell().Element(c => HeaderCellStyle(c)).Text("Previous").FontSize(9).Bold();
                                header.Cell().Element(c => HeaderCellStyle(c)).Text("New Salary").FontSize(9).Bold();
                                header.Cell().Element(c => HeaderCellStyle(c)).Text("Change %").FontSize(9).Bold();
                                header.Cell().Element(c => HeaderCellStyle(c)).Text("Status").FontSize(9).Bold();
                                header.Cell().Element(c => HeaderCellStyle(c)).Text("Reason").FontSize(9).Bold();
                                header.Cell().Element(c => HeaderCellStyle(c)).Text("Approved By").FontSize(9).Bold();
                            });

                            var histIndex = 0;
                            foreach (var entry in history.OrderBy(h => h.EffectiveDate))
                            {
                                var bgColor = histIndex % 2 == 0 ? global::QuestPDF.Helpers.Colors.White : global::QuestPDF.Helpers.Colors.Grey.Lighten4;
                                table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text(entry.EffectiveDate.ToString("MMMM dd, yyyy")).FontSize(8);
                                table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text($"₱{entry.PreviousTotalSalary:N2}").FontSize(8);
                                table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text($"₱{entry.NewTotalSalary:N2}").FontSize(8);
                                table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text($"{entry.ChangePercentage:F2}%").FontSize(8);
                                table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text(entry.Status).FontSize(8);
                                table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text(entry.Reason ?? "N/A").FontSize(8);
                                table.Cell().Element(c => CellStyle(c).Background(bgColor)).Text(entry.ApproverName ?? "—").FontSize(8);
                                histIndex++;
                            }
                        });
                    });

                page.Footer()
                    .PaddingTop(10)
                    .BorderTop(1).BorderColor(global::QuestPDF.Helpers.Colors.Grey.Lighten2)
                    .Row(row =>
                    {
                        row.RelativeItem().Text("Confidential — For Internal Use Only").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Medium);
                        row.RelativeItem().AlignCenter().Text($"Generated by {generatedBy} on {DateTime.Now:MMMM dd, yyyy}").FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Medium);
                        row.RelativeItem().AlignRight()
                            .DefaultTextStyle(x => x.FontSize(8).FontColor(global::QuestPDF.Helpers.Colors.Grey.Medium))
                            .Text(x =>
                            {
                                x.Span("Page ");
                                x.CurrentPageNumber();
                                x.Span(" of ");
                                x.TotalPages();
                            });
                    });
            });
        }).GeneratePdf();
    }

    private static global::QuestPDF.Infrastructure.IContainer CellStyle(global::QuestPDF.Infrastructure.IContainer container)
    {
        return container
            .Border(1)
            .BorderColor(global::QuestPDF.Helpers.Colors.Grey.Lighten2)
            .Padding(5)
            .Background(global::QuestPDF.Helpers.Colors.White);
    }

    private static global::QuestPDF.Infrastructure.IContainer HeaderCellStyle(global::QuestPDF.Infrastructure.IContainer container)
    {
        return container
            .Border(1)
            .BorderColor(global::QuestPDF.Helpers.Colors.Grey.Lighten2)
            .Padding(5)
            .Background(global::QuestPDF.Helpers.Colors.Blue.Lighten4);
    }

    private StatisticalData CalculateStatistics(List<SalaryChangeLogDto> data)
    {
        var stats = new StatisticalData();
        
        stats.TotalChanges = data.Count;
        var approved = data.Count(d => d.Status == "Approved");
        stats.ApprovalRate = stats.TotalChanges > 0 ? (approved * 100.0 / stats.TotalChanges) : 0;
        stats.AverageIncreasePercent = data.Where(d => d.ChangePercentage > 0 && d.Status == "Approved").Any()
            ? (double)data.Where(d => d.ChangePercentage > 0 && d.Status == "Approved").Average(d => d.ChangePercentage)
            : 0;

        // Department Breakdown
        stats.DepartmentBreakdown = data
            .Where(d => d.Status == "Approved")
            .GroupBy(d => d.Role)
            .Select(g => new DepartmentStats
            {
                Department = g.Key,
                EmployeeCount = g.Select(d => d.UserId).Distinct().Count(),
                TotalIncrease = g.Sum(d => d.ChangeAmount > 0 ? d.ChangeAmount : 0),
                AverageIncreasePercent = g.Where(d => d.ChangePercentage > 0).Any() 
                    ? (double)g.Where(d => d.ChangePercentage > 0).Average(d => d.ChangePercentage) 
                    : 0,
                HighestIncreasePercent = (double)g.Max(d => d.ChangePercentage)
            })
            .OrderByDescending(d => d.TotalIncrease)
            .ToList();

        // School Year Breakdown
        stats.SchoolYearBreakdown = data
            .Where(d => d.Status == "Approved")
            .GroupBy(d => d.SchoolYear)
            .Select(g => new SchoolYearStats
            {
                SchoolYear = g.Key,
                ChangeCount = g.Count(),
                TotalIncrease = g.Sum(d => d.ChangeAmount > 0 ? d.ChangeAmount : 0),
                NetChange = g.Sum(d => d.ChangeAmount),
                AverageIncreasePercent = g.Where(d => d.ChangePercentage > 0).Any()
                    ? (double)g.Where(d => d.ChangePercentage > 0).Average(d => d.ChangePercentage)
                    : 0
            })
            .OrderByDescending(y => y.SchoolYear)
            .ToList();

        // Generate Recommendations
        stats.Recommendations = GenerateRecommendations(stats, data);

        return stats;
    }

    private List<string> GenerateRecommendations(StatisticalData stats, List<SalaryChangeLogDto> data)
    {
        var recommendations = new List<string>();

        if (stats.ApprovalRate < 70)
        {
            recommendations.Add($"Low approval rate ({stats.ApprovalRate:F1}%) suggests need for better salary change justification and threshold management.");
        }

        if (stats.AverageIncreasePercent > 15)
        {
            recommendations.Add($"High average increase ({stats.AverageIncreasePercent:F2}%) may indicate salary compression issues. Review market rates.");
        }

        var pendingCount = data.Count(d => d.Status == "Pending");
        if (pendingCount > 10)
        {
            recommendations.Add($"{pendingCount} pending approvals require immediate attention to maintain employee satisfaction.");
        }

        var highIncreases = data.Where(d => d.ChangePercentage > 50 && d.Status == "Approved").Count();
        if (highIncreases > 0)
        {
            recommendations.Add($"{highIncreases} salary changes exceeded 50% increase. Review for consistency and budget impact.");
        }

        var deptWithMostChanges = stats.DepartmentBreakdown.FirstOrDefault();
        if (deptWithMostChanges != null && deptWithMostChanges.TotalIncrease > 0)
        {
            recommendations.Add($"{deptWithMostChanges.Department} has the highest salary increase impact (₱{deptWithMostChanges.TotalIncrease:N2}). Monitor budget allocation.");
        }

        if (recommendations.Count == 0)
        {
            recommendations.Add("Salary change patterns appear normal. Continue monitoring for consistency.");
        }

        return recommendations;
    }
}

// Supporting classes for statistics
public class StatisticalData
{
    public int TotalChanges { get; set; }
    public double ApprovalRate { get; set; }
    public double AverageIncreasePercent { get; set; }
    public List<DepartmentStats> DepartmentBreakdown { get; set; } = new();
    public List<SchoolYearStats> SchoolYearBreakdown { get; set; } = new();
    public List<string> Recommendations { get; set; } = new();
}

public class DepartmentStats
{
    public string Department { get; set; } = string.Empty;
    public int EmployeeCount { get; set; }
    public decimal TotalIncrease { get; set; }
    public double AverageIncreasePercent { get; set; }
    public double HighestIncreasePercent { get; set; }
}

public class SchoolYearStats
{
    public string SchoolYear { get; set; } = string.Empty;
    public int ChangeCount { get; set; }
    public decimal TotalIncrease { get; set; }
    public decimal NetChange { get; set; }
    public double AverageIncreasePercent { get; set; }
}
