using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.IO;
using BrightEnroll_DES.Services.Business.SuperAdmin;
using BrightEnroll_DES.Data.Models.SuperAdmin;
using QuestPdfColors = QuestPDF.Helpers.Colors;

namespace BrightEnroll_DES.Services.QuestPDF;

public class SuperAdminSalesPdfGenerator
{
    private byte[]? _logoBytes;

    private byte[] GetLogoBytes()
    {
        if (_logoBytes != null) return _logoBytes;
        
        var logoPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "reportPDF.png");
        if (File.Exists(logoPath))
        {
            _logoBytes = File.ReadAllBytes(logoPath);
        }
        return _logoBytes ?? Array.Empty<byte>();
    }

    public byte[] GenerateSalesReport(
        SalesReportData data,
        string generatedBy,
        DateTime? dateFrom = null,
        DateTime? dateTo = null)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(1.5f, Unit.Centimetre);
                page.PageColor(QuestPdfColors.White);
                page.DefaultTextStyle(x => x.FontSize(10));

                // Header
                page.Header().Row(row =>
                {
                    var logoBytes = GetLogoBytes();
                    if (logoBytes.Length > 0)
                    {
                        row.ConstantItem(80).Image(logoBytes).FitArea();
                    }
                    row.RelativeItem(8).Column(column =>
                    {
                        column.Item().Text("Sales & Revenue Report").FontSize(16).Bold();
                        column.Item().Text($"Generated: {DateTime.Now:MMMM dd, yyyy 'at' HH:mm}").FontSize(9);
                        if (dateFrom.HasValue && dateTo.HasValue)
                        {
                            column.Item().Text($"Period: {dateFrom.Value:MMM dd, yyyy} to {dateTo.Value:MMM dd, yyyy}").FontSize(9);
                        }
                        column.Item().Text($"Generated by: {generatedBy}").FontSize(9);
                    });
                });

                // Content
                page.Content().PaddingVertical(10).Column(column =>
                {
                    // Summary Stats
                    column.Item().PaddingBottom(10).Row(row =>
                    {
                        row.ConstantItem(150).Background(QuestPdfColors.Blue.Lighten5).Padding(8).Column(col =>
                        {
                            col.Item().Text("Total Revenue").FontSize(9).Bold();
                            col.Item().Text($"₱{data.TotalRevenue:N2}").FontSize(14).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                            if (data.TotalVAT > 0)
                            {
                                col.Item().PaddingTop(2).Text($"Subtotal: ₱{data.TotalSubtotal:N2}").FontSize(7);
                                col.Item().Text($"VAT: ₱{data.TotalVAT:N2}").FontSize(7);
                            }
                        });
                        row.ConstantItem(10);
                        row.ConstantItem(150).Background(QuestPdfColors.Green.Lighten5).Padding(8).Column(col =>
                        {
                            col.Item().Text("Converted Sales").FontSize(9).Bold();
                            col.Item().Text($"{data.ConvertedSales}").FontSize(14).Bold().FontColor(QuestPdfColors.Green.Darken2);
                        });
                        row.ConstantItem(10);
                        row.ConstantItem(150).Background(QuestPdfColors.Orange.Lighten5).Padding(8).Column(col =>
                        {
                            col.Item().Text("Active Leads").FontSize(9).Bold();
                            col.Item().Text($"{data.ActiveLeads}").FontSize(14).Bold().FontColor(QuestPdfColors.Orange.Darken2);
                        });
                    });

                    // A/R Summary
                    if (data.AccountsReceivable != null && data.AccountsReceivable.Total > 0)
                    {
                        column.Item().PaddingTop(10).Text("Accounts Receivable Summary").FontSize(12).Bold();
                        column.Item().PaddingTop(5).Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn();
                                columns.RelativeColumn();
                            });
                            table.Header(header =>
                            {
                                header.Cell().Background(QuestPdfColors.Grey.Lighten3).Padding(5).Text("Aging Bucket").Bold();
                                header.Cell().Background(QuestPdfColors.Grey.Lighten3).Padding(5).AlignRight().Text("Amount").Bold();
                            });
                            table.Cell().Padding(5).Text("Current");
                            table.Cell().Padding(5).AlignRight().Text($"₱{data.AccountsReceivable.Current:N2}");
                            table.Cell().Padding(5).Text("1-30 Days");
                            table.Cell().Padding(5).AlignRight().Text($"₱{data.AccountsReceivable.Days1_30:N2}");
                            table.Cell().Padding(5).Text("31-60 Days");
                            table.Cell().Padding(5).AlignRight().Text($"₱{data.AccountsReceivable.Days31_60:N2}");
                            table.Cell().Padding(5).Text("61-90 Days");
                            table.Cell().Padding(5).AlignRight().Text($"₱{data.AccountsReceivable.Days61_90:N2}");
                            table.Cell().Padding(5).Text("Over 90 Days");
                            table.Cell().Padding(5).AlignRight().Text($"₱{data.AccountsReceivable.DaysOver90:N2}");
                            table.Cell().Background(QuestPdfColors.Grey.Lighten4).Padding(5).Text("Total A/R").Bold();
                            table.Cell().Background(QuestPdfColors.Grey.Lighten4).Padding(5).AlignRight().Text($"₱{data.AccountsReceivable.Total:N2}").Bold();
                        });
                    }

                    // Recent Conversions
                    if (data.RecentConversions != null && data.RecentConversions.Any())
                    {
                        column.Item().PaddingTop(10).Text("Recent Conversions").FontSize(12).Bold();
                        column.Item().PaddingTop(5).Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(2);
                                columns.RelativeColumn();
                                columns.RelativeColumn();
                                columns.RelativeColumn();
                            });
                            table.Header(header =>
                            {
                                header.Cell().Background(QuestPdfColors.Grey.Lighten3).Padding(5).Text("School").Bold();
                                header.Cell().Background(QuestPdfColors.Grey.Lighten3).Padding(5).Text("Plan").Bold();
                                header.Cell().Background(QuestPdfColors.Grey.Lighten3).Padding(5).Text("Date").Bold();
                                header.Cell().Background(QuestPdfColors.Grey.Lighten3).Padding(5).AlignRight().Text("Amount").Bold();
                            });
                            foreach (var sale in data.RecentConversions.Take(20))
                            {
                                table.Cell().Padding(5).Text(sale.SchoolName).FontSize(8);
                                table.Cell().Padding(5).Text(sale.Plan).FontSize(8);
                                table.Cell().Padding(5).Text(sale.ConversionDate.ToString("MMM dd, yyyy")).FontSize(8);
                                table.Cell().Padding(5).AlignRight().Text($"₱{sale.Amount:N2}").FontSize(8);
                            }
                        });
                    }
                });

                // Footer
                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span($"Page ");
                    text.CurrentPageNumber();
                    text.Span(" of ");
                    text.TotalPages();
                    text.Span($" | © {DateTime.Now.Year} BrightEnroll. All rights reserved.");
                });
            });
        }).GeneratePdf();
    }

    public byte[] GenerateAccountsReceivableReport(
        List<AccountsReceivableSummary> arData,
        AgingReport agingReport,
        string generatedBy,
        DateTime? asOfDate = null)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(1.5f, Unit.Centimetre);
                page.PageColor(QuestPdfColors.White);
                page.DefaultTextStyle(x => x.FontSize(10));

                // Header
                page.Header().Row(row =>
                {
                    var logoBytes = GetLogoBytes();
                    if (logoBytes.Length > 0)
                    {
                        row.ConstantItem(80).Image(logoBytes).FitArea();
                    }
                    row.RelativeItem(8).Column(column =>
                    {
                        column.Item().Text("Accounts Receivable Report").FontSize(16).Bold();
                        column.Item().Text($"As of: {(asOfDate ?? DateTime.Now):MMMM dd, yyyy}").FontSize(9);
                        column.Item().Text($"Generated: {DateTime.Now:MMMM dd, yyyy 'at' HH:mm}").FontSize(9);
                        column.Item().Text($"Generated by: {generatedBy}").FontSize(9);
                    });
                });

                // Content
                page.Content().PaddingVertical(10).Column(column =>
                {
                    // Aging Summary
                    column.Item().PaddingBottom(10).Row(row =>
                    {
                        row.ConstantItem(150).Background(QuestPdfColors.Blue.Lighten5).Padding(8).Column(col =>
                        {
                            col.Item().Text("Total A/R").FontSize(9).Bold();
                            col.Item().Text($"₱{agingReport.Total:N2}").FontSize(14).Bold().FontColor(QuestPdfColors.Blue.Darken2);
                        });
                        row.ConstantItem(10);
                        row.ConstantItem(150).Background(QuestPdfColors.Orange.Lighten5).Padding(8).Column(col =>
                        {
                            col.Item().Text("Overdue (>90)").FontSize(9).Bold();
                            col.Item().Text($"₱{agingReport.DaysOver90:N2}").FontSize(14).Bold().FontColor(QuestPdfColors.Orange.Darken2);
                        });
                    });

                    // Aging Bucket Table
                    column.Item().PaddingTop(10).Text("Aging Analysis").FontSize(12).Bold();
                    column.Item().PaddingTop(5).Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                        });
                        table.Header(header =>
                        {
                            header.Cell().Background(QuestPdfColors.Grey.Lighten3).Padding(5).Text("Aging Bucket").Bold();
                            header.Cell().Background(QuestPdfColors.Grey.Lighten3).Padding(5).AlignRight().Text("Amount").Bold();
                        });
                        table.Cell().Padding(5).Text("Current");
                        table.Cell().Padding(5).AlignRight().Text($"₱{agingReport.Current:N2}");
                        table.Cell().Padding(5).Text("1-30 Days");
                        table.Cell().Padding(5).AlignRight().Text($"₱{agingReport.Days1_30:N2}");
                        table.Cell().Padding(5).Text("31-60 Days");
                        table.Cell().Padding(5).AlignRight().Text($"₱{agingReport.Days31_60:N2}");
                        table.Cell().Padding(5).Text("61-90 Days");
                        table.Cell().Padding(5).AlignRight().Text($"₱{agingReport.Days61_90:N2}");
                        table.Cell().Padding(5).Text("Over 90 Days");
                        table.Cell().Padding(5).AlignRight().Text($"₱{agingReport.DaysOver90:N2}");
                        table.Cell().Background(QuestPdfColors.Grey.Lighten4).Padding(5).Text("Total").Bold();
                        table.Cell().Background(QuestPdfColors.Grey.Lighten4).Padding(5).AlignRight().Text($"₱{agingReport.Total:N2}").Bold();
                    });

                    // Customer Details
                    if (arData.Any())
                    {
                        column.Item().PaddingTop(15).Text("Customer A/R Details").FontSize(12).Bold();
                        column.Item().PaddingTop(5).Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(2);
                                columns.RelativeColumn();
                                columns.RelativeColumn();
                                columns.RelativeColumn();
                                columns.RelativeColumn();
                            });
                            table.Header(header =>
                            {
                                header.Cell().Background(QuestPdfColors.Grey.Lighten3).Padding(5).Text("Customer").Bold().FontSize(8);
                                header.Cell().Background(QuestPdfColors.Grey.Lighten3).Padding(5).Text("Balance").Bold().FontSize(8);
                                header.Cell().Background(QuestPdfColors.Grey.Lighten3).Padding(5).Text("Days Overdue").Bold().FontSize(8);
                                header.Cell().Background(QuestPdfColors.Grey.Lighten3).Padding(5).Text("Aging").Bold().FontSize(8);
                                header.Cell().Background(QuestPdfColors.Grey.Lighten3).Padding(5).Text("Status").Bold().FontSize(8);
                            });
                            foreach (var ar in arData.Take(30))
                            {
                                table.Cell().Padding(5).Text(ar.CustomerName).FontSize(8);
                                table.Cell().Padding(5).AlignRight().Text($"₱{ar.Balance:N2}").FontSize(8);
                                table.Cell().Padding(5).AlignRight().Text(ar.DaysOverdue.ToString()).FontSize(8);
                                table.Cell().Padding(5).Text(ar.AgingBucket).FontSize(8);
                                table.Cell().Padding(5).Text(ar.Status).FontSize(8);
                            }
                        });
                    }
                });

                // Footer
                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span($"Page ");
                    text.CurrentPageNumber();
                    text.Span(" of ");
                    text.TotalPages();
                    text.Span($" | © {DateTime.Now.Year} BrightEnroll. All rights reserved.");
                });
            });
        }).GeneratePdf();
    }
}

public class SalesReportData
{
    public decimal TotalRevenue { get; set; }
    public decimal TotalSubtotal { get; set; }
    public decimal TotalVAT { get; set; }
    public int ActiveLeads { get; set; }
    public int ConvertedSales { get; set; }
    public List<SaleConversionData>? RecentConversions { get; set; }
    public AgingReport? AccountsReceivable { get; set; }
}

public class SaleConversionData
{
    public string SchoolName { get; set; } = string.Empty;
    public string Plan { get; set; } = string.Empty;
    public DateTime ConversionDate { get; set; }
    public decimal Amount { get; set; }
}
